<form method="POST" action="{{ $action }}" enctype="multipart/form-data" class="space-y-5">@csrf @if($method!=='POST') @method($method) @endif
<div class="grid gap-4 md:grid-cols-2">
    <div><label class="mb-1 block text-xs text-slate-400">Kategori</label><select name="chain_menu_category_id" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5">@foreach($categories as $categoryOption)<option value="{{ $categoryOption->id }}" @selected($editingProduct?->chain_menu_category_id===$categoryOption->id)>{{ $categoryOption->name }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-xs text-slate-400">SKU / Ürün Kodu</label><input name="sku" required value="{{ $editingProduct?->sku }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 uppercase"></div>
    <div><label class="mb-1 block text-xs text-slate-400">Ürün Adı</label><input name="name" required value="{{ $editingProduct?->name }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"></div>
    <div><label class="mb-1 block text-xs text-slate-400">Mutfak Departmanı</label><input name="kitchen_department" value="{{ $editingProduct?->kitchen_department }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"></div>
    <div><label class="mb-1 block text-xs text-slate-400">Merkez Fiyatı</label><input type="number" step="0.01" min="0" name="base_price" required value="{{ $editingProduct?->base_price }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"></div>
    <div><label class="mb-1 block text-xs text-slate-400">İndirimli Fiyat</label><input type="number" step="0.01" min="0" name="discounted_price" value="{{ $editingProduct?->discounted_price }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"></div>
</div>
<div class="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><div class="grid gap-4 md:grid-cols-[160px_1fr]">@php($currentImage=$editingProduct?->image_path) <div class="flex aspect-square items-center justify-center overflow-hidden rounded-xl border border-slate-800 bg-slate-900">@if($currentImage)<img src="{{ \Illuminate\Support\Str::startsWith($currentImage,['http://','https://'])?$currentImage:asset($currentImage) }}" class="h-full w-full object-cover" alt="{{ $editingProduct?->name }} görseli">@else<div class="text-center text-slate-600"><svg class="mx-auto h-9 w-9" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="1.5" d="m3 16 5-5 4 4 3-3 6 6M5 21h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2Z"/></svg><span class="mt-2 block text-[10px]">Görsel yok</span></div>@endif</div><div class="space-y-3"><div><label class="mb-1 block text-xs font-semibold text-slate-300">Bilgisayardan Fotoğraf Yükle</label><input type="file" name="image_file" accept="image/jpeg,image/png,image/webp" class="w-full rounded-lg border border-dashed border-cyan-500/30 bg-cyan-500/5 p-3 text-xs file:mr-3 file:rounded-md file:border-0 file:bg-cyan-500 file:px-3 file:py-2 file:font-semibold file:text-slate-950"><p class="mt-1 text-[10px] text-slate-500">JPG, PNG veya WebP · en fazla 5 MB · minimum 300×300 px</p></div><div><label class="mb-1 block text-xs text-slate-400">veya Görsel URL</label><input type="url" name="image_path" value="{{ \Illuminate\Support\Str::startsWith($currentImage,['http://','https://'])?$currentImage:'' }}" placeholder="https://..." class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>@if($currentImage)<label class="flex items-center gap-2 text-xs text-rose-400"><input type="checkbox" name="remove_image" value="1"> Mevcut görseli kaldır</label>@endif</div></div></div>
<div><label class="mb-1 block text-xs text-slate-400">Açıklama</label><textarea name="description" rows="2" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5">{{ $editingProduct?->description }}</textarea></div>
<label class="flex gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($editingProduct?->is_active ?? true)> Ürün merkezde aktif</label>
<div><p class="mb-1 text-xs font-bold text-slate-300">Şube Ataması ve Fiyat İstisnaları</p><p class="mb-3 text-[11px] text-slate-500">Şubeyi seçin; fiyat boşsa merkez fiyatı kullanılır. “Satışta” kapalıysa ürün şubede pasif yayınlanır.</p><div class="space-y-2 rounded-xl border border-slate-800 bg-slate-950 p-3">
@foreach($branches as $branch) @php($assignment=$editingProduct?->branches->firstWhere('id',$branch->id)?->pivot)
<div class="grid grid-cols-[auto_1fr_120px_auto] items-center gap-3 rounded-lg border border-slate-800 p-3"><input type="checkbox" name="branch_ids[]" value="{{ $branch->id }}" @checked((bool)$assignment)><div><strong class="block text-sm">{{ $branch->name }}</strong><span class="text-[11px] text-slate-600">{{ $branch->code }}</span></div><input type="number" step="0.01" min="0" name="price_overrides[{{ $branch->id }}]" value="{{ $assignment?->price_override }}" placeholder="Özel fiyat" class="w-full rounded-lg border border-slate-700 bg-slate-900 p-2 text-xs"><label class="flex gap-1 text-xs text-slate-400"><input type="checkbox" name="enabled_branch_ids[]" value="{{ $branch->id }}" @checked($assignment?->is_enabled ?? true)> Satışta</label></div>
@endforeach
</div></div>
<button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Taslağı Kaydet</button>
</form>
