@extends('chain.layout')
@section('title','Stoklar & Transfer')
@section('content')
<div class="space-y-6">
<div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="institutional-page-kicker mb-1">Lojistik Yönetimi</p><h1>Merkez Depo ve Şube Stokları</h1><p class="mt-1 text-sm text-slate-400">Genel stoğu merkeze alın, kontrollü biçimde şubelere dağıtın.</p></div>@if($canTransfer)<div class="flex flex-wrap gap-2"><button type="button" onclick="openCentralStock()" class="institutional-action inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-bold text-slate-950"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="2" d="M12 5v14M5 12h14"/></svg>Merkez Stok Girişi</button><button type="button" onclick="openCentralDistribution()" class="institutional-action inline-flex items-center gap-2 rounded-lg bg-cyan-500 px-4 py-2.5 text-sm font-bold text-slate-950"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="1.8" d="M4 7h10m0 0-3-3m3 3-3 3M20 17H10m0 0 3-3m-3 3 3 3"/></svg>Şubelere Dağıt</button><button type="button" onclick="openStockEntry()" class="institutional-action rounded-lg border border-slate-700 px-3 py-2.5 text-sm text-slate-400">Şube Düzeltmesi</button><button type="button" onclick="openStockTransfer()" class="institutional-action rounded-lg border border-slate-700 px-3 py-2.5 text-sm text-slate-400">Şubeler Arası Transfer</button></div>@endif</div>
@if($errors->any())<div class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{{ $errors->first() }}</div>@endif

@php($centralCritical=$centralProducts->filter(fn($product)=>(float)$product->stock_quantity<=(float)$product->min_stock_level)->count())
<section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">
    <div class="flex flex-col gap-3 border-b border-slate-800 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-black">Merkez F&amp;B Stok Deposu</h2><p class="mt-1 text-xs text-slate-500">{{ $centralProducts->count() }} hammadde · <span class="{{ $centralCritical ? 'text-rose-400' : 'text-emerald-400' }}">{{ $centralCritical }} kritik stok</span></p></div><label class="relative"><svg class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="1.8" d="m21 21-4.5-4.5m2.5-5.5a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z"/></svg><input id="centralStockSearch" type="search" placeholder="Hammadde ara..." class="w-full rounded-lg border border-slate-700 bg-slate-950 py-2.5 pl-10 pr-3 text-sm sm:w-72"></label></div>
    <div class="max-h-[430px] overflow-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="sticky top-0 z-10 bg-slate-950/95 text-[11px] uppercase text-slate-500"><tr><th class="px-4 py-3">Hammadde</th><th class="px-4 py-3">Birim</th><th class="px-4 py-3 text-right">Merkez Stok</th><th class="px-4 py-3 text-right">Kritik Seviye</th><th class="px-4 py-3">Durum</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($centralProducts as $product)<tr data-central-row data-search="{{ $product->name }} {{ $product->sku }}" class="hover:bg-slate-800/30"><td class="px-4 py-3"><div class="flex items-center gap-3"><div class="h-10 w-10 overflow-hidden rounded-lg border border-slate-800 bg-slate-950">@if($product->image_path)<img src="{{ asset($product->image_path) }}" alt="" class="h-full w-full object-cover">@endif</div><div><strong class="block">{{ $product->name }}</strong><small class="font-mono text-slate-500">{{ $product->sku }}</small></div></div></td><td class="px-4 py-3 text-slate-500">{{ $product->unit }}</td><td class="px-4 py-3 text-right text-lg font-black {{ (float)$product->stock_quantity<=(float)$product->min_stock_level?'text-rose-400':'text-emerald-400' }}">{{ number_format((float)$product->stock_quantity,3,',','.') }}</td><td class="px-4 py-3 text-right text-slate-500">{{ number_format((float)$product->min_stock_level,3,',','.') }} {{ $product->unit }}</td><td class="px-4 py-3"><span class="inline-flex items-center gap-1.5 text-xs {{ (float)$product->stock_quantity<=(float)$product->min_stock_level?'text-rose-400':'text-emerald-400' }}"><i class="h-1.5 w-1.5 rounded-full bg-current"></i>{{ (float)$product->stock_quantity<=(float)$product->min_stock_level?'Kritik':'Yeterli' }}</span></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">Merkez depoda hammadde bulunamadı.</td></tr>@endforelse</tbody></table></div>
</section>

@if($centralMovements->isNotEmpty())
<details class="rounded-2xl border border-slate-800 bg-slate-900"><summary class="cursor-pointer px-4 py-3 text-sm font-bold">Merkez Depo Hareketleri <span class="ml-2 text-xs font-normal text-slate-500">Son {{ $centralMovements->count() }} işlem</span></summary><div class="max-h-72 overflow-auto border-t border-slate-800"><table class="w-full min-w-[720px] text-left text-xs"><thead class="bg-slate-950/50 text-slate-500"><tr><th class="px-4 py-2">Tarih</th><th class="px-4 py-2">Ürün</th><th class="px-4 py-2">İşlem</th><th class="px-4 py-2">Şube</th><th class="px-4 py-2 text-right">Miktar</th><th class="px-4 py-2 text-right">Kalan</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($centralMovements as $movement)<tr><td class="px-4 py-2 text-slate-500">{{ $movement->created_at->format('d.m.Y H:i') }}</td><td class="px-4 py-2 font-semibold">{{ $movement->product?->name }}</td><td class="px-4 py-2">{{ ['central_addition'=>'Stok girişi','central_subtraction'=>'Stok çıkışı','stock_count'=>'Sayım düzeltmesi','distribution_out'=>'Şubeye dağıtım'][$movement->type]??$movement->type }}</td><td class="px-4 py-2 text-slate-500">{{ $movement->branch?->name ?? 'Merkez Depo' }}</td><td class="px-4 py-2 text-right">{{ number_format((float)$movement->quantity,3,',','.') }} {{ $movement->unit }}</td><td class="px-4 py-2 text-right font-bold">{{ number_format((float)$movement->stock_after,3,',','.') }} {{ $movement->unit }}</td></tr>@endforeach</tbody></table></div></details>
@endif

<section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="font-black">Şubeler Arası Stok Matrisi</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Ürün</th>@foreach($branches as $branch)<th class="p-4">{{ $branch->name }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-800">@forelse($stockRows as $row)<tr><td class="p-4"><strong>{{ $row->name }}</strong><small class="block font-mono text-cyan-500">{{ $row->sku }}</small></td>@foreach($branches as $branch) @php($product=$row->branches[$branch->id]) <td class="p-4">@if($product)<span class="font-black {{ (float)$product->stock_quantity <= (float)$product->min_stock_level ? 'text-rose-400':'text-emerald-400' }}">{{ number_format((float)$product->stock_quantity,2,',','.') }}</span> <small class="text-slate-500">{{ $product->unit }}</small>@else<span class="text-slate-700">—</span>@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ $branches->count()+1 }}" class="p-8 text-center text-slate-500">Stok takibi yapılan ürün bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

<section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="font-black">Transferler</h2></div><div class="space-y-3 p-4">@forelse($transfers as $transfer)
<article class="rounded-xl border border-slate-800 bg-slate-950 p-4"><div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div class="flex items-center gap-2"><strong>{{ $transfer->transfer_number }}</strong><span class="rounded-full bg-slate-800 px-2 py-1 text-[10px] uppercase text-cyan-300">{{ ['requested'=>'Talep','approved'=>'Onaylandı','shipped'=>'Sevkte','received'=>'Teslim','cancelled'=>'İptal'][$transfer->status]??$transfer->status }}</span></div><p class="mt-1 text-sm text-slate-400">{{ $transfer->sourceBranch->name }} → {{ $transfer->targetBranch->name }}</p><p class="mt-1 text-xs text-slate-600">{{ $transfer->items->map(fn($i)=>$i->product_name.' ('.rtrim(rtrim(number_format((float)$i->quantity,3,'.',''),'0'),'.').' '.$i->unit.')')->join(', ') }}</p></div>@if($canTransfer)<div class="flex flex-wrap gap-2">@if($transfer->status==='requested')<form method="POST" action="{{ route('chain.stock-transfers.approve',$transfer) }}">@csrf<button class="rounded-lg bg-indigo-500 px-3 py-2 text-xs font-bold">Onayla</button></form>@endif @if($transfer->status==='approved')<form method="POST" action="{{ route('chain.stock-transfers.ship',$transfer) }}">@csrf<button class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-slate-950">Sevk Et</button></form>@endif @if($transfer->status==='shipped')<form method="POST" action="{{ route('chain.stock-transfers.receive',$transfer) }}">@csrf<button class="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950">Teslim Al</button></form>@endif @if(in_array($transfer->status,['requested','approved']))<form method="POST" action="{{ route('chain.stock-transfers.cancel',$transfer) }}" onsubmit="return confirm('Transfer iptal edilsin mi?')">@csrf<button class="rounded-lg border border-rose-500/30 px-3 py-2 text-xs text-rose-300">İptal</button></form>@endif</div>@endif</div></article>
@empty<p class="p-8 text-center text-sm text-slate-500">Henüz transfer yok.</p>@endforelse</div><div class="border-t border-slate-800 p-4">{{ $transfers->links() }}</div></section>
</div>
@if($canTransfer)<div id="transferModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4"><div class="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6"><div class="mb-5 flex justify-between"><h3 class="font-black">Yeni Stok Transferi</h3><button onclick="closeStockTransfer()">✕</button></div><form method="POST" action="{{ route('chain.stock-transfers.store') }}" class="space-y-4">@csrf<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-xs text-slate-400">Kaynak Şube</label><select id="sourceBranch" name="source_branch_id" required onchange="filterTransferProducts()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs text-slate-400">Hedef Şube</label><select name="target_branch_id" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div></div><div><label class="mb-1 block text-xs text-slate-400">Ürün</label><select name="items[0][product_id]" id="transferProduct" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Önce kaynak şubeyi seçin</option>@foreach($products as $product)<option class="product-option" data-branch="{{ $product->branch_id }}" value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }} · Stok {{ $product->stock_quantity }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs text-slate-400">Miktar</label><input type="number" step="0.001" min="0.001" name="items[0][quantity]" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></div><div><label class="mb-1 block text-xs text-slate-400">Not</label><textarea name="notes" rows="2" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></textarea></div><button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Transfer Talebi Oluştur</button></form></div></div>@endif
@if($canTransfer)
<div id="centralStockModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div class="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-5 shadow-2xl sm:p-6"><div class="mb-5 flex items-start justify-between"><div><p class="institutional-page-kicker mb-1">Merkez F&amp;B Deposu</p><h3 class="font-black">Merkez Stok İşlemi</h3><p class="mt-1 text-xs text-slate-500">Mal kabulünü merkeze girin veya sayım sonucunu düzeltin.</p></div><button type="button" onclick="closeCentralStock()" class="rounded-lg p-2 text-slate-400 hover:bg-slate-800">✕</button></div><form method="POST" action="{{ route('chain.stocks.central.adjust') }}" class="space-y-4">@csrf<input type="hidden" name="form_context" value="central_stock"><div><label class="mb-1 block text-xs text-slate-400">Hammadde</label><select id="centralStockProduct" name="product_id" required onchange="updateCentralStockInfo()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Ürün seçin</option>@foreach($centralProducts as $product)<option value="{{ $product->id }}" data-unit="{{ $product->unit }}" data-current="{{ (float)$product->stock_quantity }}" @selected(old('product_id')==$product->id)>{{ $product->name }} · {{ $product->sku }}</option>@endforeach</select><p id="centralStockCurrent" class="mt-1.5 text-xs text-slate-500">Merkez mevcut stok: —</p></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-xs text-slate-400">İşlem</label><select id="centralStockOperation" name="operation" required onchange="updateCentralStockLabel()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="add">Merkeze Stok Girişi (+)</option><option value="subtract">Merkez Stok Çıkışı (-)</option><option value="set">Sayım Sonucunu Belirle</option></select></div><div><label id="centralStockQuantityLabel" class="mb-1 block text-xs text-slate-400">Giriş Miktarı</label><div class="relative"><input name="quantity" type="number" step="0.001" min="0" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 pr-14"><span id="centralStockUnit" class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-cyan-500">—</span></div></div></div><div><label class="mb-1 block text-xs text-slate-400">Kritik Stok Seviyesi <span class="text-slate-600">(opsiyonel)</span></label><input name="min_stock_level" type="number" step="0.001" min="0" placeholder="Değiştirme" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></div><div><label class="mb-1 block text-xs text-slate-400">Açıklama / İrsaliye No</label><textarea name="notes" rows="2" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></textarea></div><button class="w-full rounded-xl bg-emerald-500 py-3 font-black text-slate-950">Merkez Stok İşlemini Kaydet</button></form></div></div>

<div id="centralDistributionModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div class="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-5 shadow-2xl sm:p-6"><div class="mb-5 flex items-start justify-between"><div><p class="institutional-page-kicker mb-1">Merkezden Şubelere</p><h3 class="font-black">Stok Dağıtımı</h3><p class="mt-1 text-xs text-slate-500">Merkez depodaki bir ürünü istediğiniz kadar şubeye dağıtabilirsiniz.</p></div><button type="button" onclick="closeCentralDistribution()" class="rounded-lg p-2 text-slate-400 hover:bg-slate-800">✕</button></div><form method="POST" action="{{ route('chain.stocks.central.distribute') }}" onsubmit="return prepareCentralDistribution()" class="space-y-4">@csrf<input type="hidden" name="form_context" value="central_distribution"><div><label class="mb-1 block text-xs text-slate-400">Dağıtılacak Hammadde</label><select id="distributionProduct" name="product_id" required onchange="updateDistributionInfo()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Ürün seçin</option>@foreach($centralProducts as $product)<option value="{{ $product->id }}" data-unit="{{ $product->unit }}" data-current="{{ (float)$product->stock_quantity }}">{{ $product->name }} · Merkez {{ number_format((float)$product->stock_quantity,3,',','.') }} {{ $product->unit }}</option>@endforeach</select><div class="mt-2 flex items-center justify-between text-xs"><span id="distributionAvailable" class="text-slate-500">Merkez kullanılabilir: —</span><span id="distributionTotal" class="font-bold text-cyan-500">Dağıtım toplamı: 0</span></div></div><div><div class="mb-2 flex items-center justify-between"><p class="text-xs font-bold text-slate-400">Şube Miktarları</p><button type="button" onclick="addDistributionAllocationRow()" class="rounded bg-slate-800 px-2 py-1 text-[10px] uppercase text-cyan-400">+ Şube Ekle</button></div><div id="distributionAllocationsContainer" class="space-y-2 rounded-xl border border-slate-800 bg-slate-950 p-3"><p class="text-center text-xs text-slate-500" id="emptyDistributionState">Dağıtılacak şube ekleyin.</p></div></div><div><label class="mb-1 block text-xs text-slate-400">Dağıtım Notu</label><textarea name="notes" rows="2" placeholder="Sevkiyat veya belge bilgisi..." class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></textarea></div><div id="distributionWarning" class="hidden rounded-lg border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-400"></div><button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Dağıtımı Tamamla</button></form></div></div>

<div id="stockEntryModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true">
    <div class="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-5 shadow-2xl sm:p-6">
        <div class="mb-5 flex items-start justify-between"><div><p class="institutional-page-kicker mb-1">Merkezi Stok Yönetimi</p><h3 class="font-black">Şube Stok Girişi</h3><p class="mt-1 text-xs text-slate-500">Kg, litre veya adet bazında stok ekleyin, çıkarın ya da sayım sonucunu belirleyin.</p></div><button type="button" onclick="closeStockEntry()" class="rounded-lg p-2 text-slate-400 hover:bg-slate-800" aria-label="Kapat">✕</button></div>
        <form method="POST" action="{{ route('chain.stocks.adjust') }}" class="space-y-4">@csrf<input type="hidden" name="form_context" value="stock_adjustment">
            <div class="grid gap-4 sm:grid-cols-2">
                <div><label class="mb-1 block text-xs text-slate-400">Şube</label><select id="stockEntryBranch" name="branch_id" required onchange="filterStockEntryProducts()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Şube seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id')==$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
                <div><label class="mb-1 block text-xs text-slate-400">İşlem</label><select id="stockEntryOperation" name="operation" required onchange="updateStockEntryLabel()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="add" @selected(old('operation','add')==='add')>Stok Girişi (+)</option><option value="subtract" @selected(old('operation')==='subtract')>Stok Çıkışı / Fire (-)</option><option value="set" @selected(old('operation')==='set')>Sayım Sonucunu Belirle</option></select></div>
            </div>
            <div><label class="mb-1 block text-xs text-slate-400">Ürün / Hammadde</label><select id="stockEntryProduct" name="product_id" required onchange="updateStockProductInfo()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Önce şube seçin</option>@foreach($products as $product)<option class="stock-entry-product" data-branch="{{ $product->branch_id }}" data-unit="{{ $product->unit }}" data-current="{{ (float)$product->stock_quantity }}" value="{{ $product->id }}" @selected(old('product_id')==$product->id)>{{ $product->name }} · {{ $product->sku }}</option>@endforeach</select><p id="stockEntryCurrent" class="mt-1.5 text-xs text-slate-500">Mevcut stok: —</p></div>
            <div class="grid gap-4 sm:grid-cols-2">
                <div><label id="stockEntryQuantityLabel" class="mb-1 block text-xs text-slate-400">Giriş Miktarı</label><div class="relative"><input type="number" step="0.001" min="0" name="quantity" value="{{ old('quantity') }}" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 pr-14"><span id="stockEntryUnit" class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-cyan-500">—</span></div></div>
                <div><label class="mb-1 block text-xs text-slate-400">Kritik Stok Seviyesi <span class="text-slate-600">(opsiyonel)</span></label><input type="number" step="0.001" min="0" name="min_stock_level" value="{{ old('min_stock_level') }}" placeholder="Değiştirme" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></div>
            </div>
            <div><label class="mb-1 block text-xs text-slate-400">Açıklama / Belge No</label><textarea name="notes" rows="2" placeholder="Örn. 02.08.2026 mal kabulü, irsaliye no..." class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3">{{ old('notes') }}</textarea></div>
            <div class="rounded-lg border border-cyan-500/20 bg-cyan-500/5 p-3 text-xs leading-5 text-slate-400">İşlem stok hareket günlüğüne yönetici, tarih, miktar ve açıklama bilgileriyle kaydedilir.</div>
            <button class="w-full rounded-xl bg-emerald-500 py-3 font-black text-slate-950">Stok İşlemini Kaydet</button>
        </form>
    </div>
</div>
@endif
<script>
function openStockTransfer(){const e=document.getElementById('transferModal');e.classList.remove('hidden');e.classList.add('flex');filterTransferProducts()}
function closeStockTransfer(){const e=document.getElementById('transferModal');e.classList.add('hidden');e.classList.remove('flex')}
function filterTransferProducts(){const b=document.getElementById('sourceBranch')?.value;document.querySelectorAll('.product-option').forEach(o=>{o.hidden=!b||o.dataset.branch!==b});document.getElementById('transferProduct').value=''}
function openStockEntry(){const e=document.getElementById('stockEntryModal');if(!e)return;e.classList.remove('hidden');e.classList.add('flex');document.body.style.overflow='hidden';filterStockEntryProducts(true)}
function closeStockEntry(){const e=document.getElementById('stockEntryModal');if(!e)return;e.classList.add('hidden');e.classList.remove('flex');document.body.style.overflow=''}
function filterStockEntryProducts(keepSelection=false){const branch=document.getElementById('stockEntryBranch')?.value;const select=document.getElementById('stockEntryProduct');document.querySelectorAll('.stock-entry-product').forEach(option=>option.hidden=!branch||option.dataset.branch!==branch);if(!keepSelection||select?.selectedOptions[0]?.hidden)select.value='';updateStockProductInfo()}
function updateStockProductInfo(){const option=document.getElementById('stockEntryProduct')?.selectedOptions[0];const unit=option?.dataset.unit||'—';const current=option?.dataset.current;document.getElementById('stockEntryUnit').textContent=unit;document.getElementById('stockEntryCurrent').textContent=current!==undefined?`Mevcut stok: ${Number(current).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit}`:'Mevcut stok: —'}
function updateStockEntryLabel(){const operation=document.getElementById('stockEntryOperation')?.value;document.getElementById('stockEntryQuantityLabel').textContent=operation==='set'?'Yeni Sayım Miktarı':(operation==='subtract'?'Çıkış / Fire Miktarı':'Giriş Miktarı')}
function openCentralStock(){const e=document.getElementById('centralStockModal');e.classList.remove('hidden');e.classList.add('flex');document.body.style.overflow='hidden';updateCentralStockInfo()}
function closeCentralStock(){const e=document.getElementById('centralStockModal');if(!e)return;e.classList.add('hidden');e.classList.remove('flex');document.body.style.overflow=''}
function updateCentralStockInfo(){const option=document.getElementById('centralStockProduct')?.selectedOptions[0];const unit=option?.dataset.unit||'—';const current=option?.dataset.current;document.getElementById('centralStockUnit').textContent=unit;document.getElementById('centralStockCurrent').textContent=current!==undefined?`Merkez mevcut stok: ${Number(current).toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit}`:'Merkez mevcut stok: —'}
function updateCentralStockLabel(){const operation=document.getElementById('centralStockOperation')?.value;document.getElementById('centralStockQuantityLabel').textContent=operation==='set'?'Yeni Sayım Miktarı':(operation==='subtract'?'Merkez Çıkış Miktarı':'Giriş Miktarı')}
function openCentralDistribution(){const e=document.getElementById('centralDistributionModal');e.classList.remove('hidden');e.classList.add('flex');document.body.style.overflow='hidden';updateDistributionInfo()}
function closeCentralDistribution(){const e=document.getElementById('centralDistributionModal');if(!e)return;e.classList.add('hidden');e.classList.remove('flex');document.body.style.overflow=''}
let distributionRowIndex = 0;
const branchOptions = `@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach`;

function updateDistributionInfo(){const option=document.getElementById('distributionProduct')?.selectedOptions[0];const unit=option?.dataset.unit||'—';const current=Number(option?.dataset.current||0);document.getElementById('distributionAvailable').textContent=option?.value?`Merkez kullanılabilir: ${current.toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit}`:'Merkez kullanılabilir: —';document.querySelectorAll('[data-distribution-unit]').forEach(e=>e.textContent=unit);updateDistributionTotal()}
function updateDistributionTotal(){const option=document.getElementById('distributionProduct')?.selectedOptions[0];const unit=option?.dataset.unit||'—';const total=[...document.querySelectorAll('[data-distribution-quantity]')].reduce((sum,input)=>sum+Number(input.value||0),0);document.getElementById('distributionTotal').textContent=`Dağıtım toplamı: ${total.toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit}`;return total}
function prepareCentralDistribution(){const option=document.getElementById('distributionProduct')?.selectedOptions[0];const available=Number(option?.dataset.current||0);const total=updateDistributionTotal();const warning=document.getElementById('distributionWarning');let message='';if(!option?.value)message='Dağıtılacak ürünü seçin.';else if(total<=0)message='En az bir şubeye sıfırdan büyük miktar girin.';else if(total>available)message='Dağıtım toplamı merkez depo stoğunu aşamaz.';warning.textContent=message;warning.classList.toggle('hidden',!message);return !message}

function addDistributionAllocationRow(){document.getElementById('emptyDistributionState')?.classList.add('hidden');const container=document.getElementById('distributionAllocationsContainer');const unit=document.getElementById('distributionProduct')?.selectedOptions[0]?.dataset.unit||'—';const div=document.createElement('div');div.className='flex items-center gap-2';div.innerHTML=`<select name="allocations[${distributionRowIndex}][branch_id]" required class="flex-1 rounded-lg border border-slate-700 bg-slate-900 p-2 text-sm"><option value="">Şube Seçin</option>${branchOptions}</select><div class="relative w-32"><input data-distribution-quantity name="allocations[${distributionRowIndex}][quantity]" type="number" step="0.001" min="0.001" required placeholder="Miktar" oninput="updateDistributionTotal()" class="w-full rounded-lg border border-slate-700 bg-slate-900 p-2 pr-8 text-sm"><span data-distribution-unit class="absolute right-2 top-1/2 -translate-y-1/2 text-[10px] text-slate-500">${unit}</span></div><button type="button" onclick="this.parentElement.remove(); updateDistributionTotal();" class="rounded p-2 text-rose-500 hover:bg-slate-800">✕</button>`;container.appendChild(div);distributionRowIndex++;}

document.getElementById('centralStockSearch')?.addEventListener('input',event=>{const query=event.target.value.toLocaleLowerCase('tr-TR').trim();document.querySelectorAll('[data-central-row]').forEach(row=>row.classList.toggle('hidden',query&&!row.dataset.search.toLocaleLowerCase('tr-TR').includes(query)))})
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeStockEntry();closeCentralStock();closeCentralDistribution()}});
@if(old('form_context')==='stock_adjustment') document.addEventListener('DOMContentLoaded',()=>openStockEntry()); @endif
@if(old('form_context')==='central_stock') document.addEventListener('DOMContentLoaded',()=>openCentralStock()); @endif
@if(old('form_context')==='central_distribution') document.addEventListener('DOMContentLoaded',()=>openCentralDistribution()); @endif
</script>
@endsection
