@extends('chain.layout')
@section('title','Stoklar & Transfer')
@section('content')
<div class="space-y-6">
<div class="flex items-center justify-between"><div><p class="institutional-page-kicker mb-1">Lojistik Yönetimi</p><h1>Stok ve Transferler</h1><p class="mt-1 text-sm text-slate-400">Şube stoklarının karşılaştırılması ve kontrollü transfer yönetimi</p></div>@if($canTransfer)<button onclick="openStockTransfer()" class="institutional-action rounded-lg bg-cyan-500 px-4 py-2.5 text-sm text-slate-950">Transfer Talebi Oluştur</button>@endif</div>
@if($errors->any())<div class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{{ $errors->first() }}</div>@endif

<section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="font-black">Şubeler Arası Stok Matrisi</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Ürün</th>@foreach($branches as $branch)<th class="p-4">{{ $branch->name }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-800">@forelse($stockRows as $row)<tr><td class="p-4"><strong>{{ $row->name }}</strong><small class="block font-mono text-cyan-500">{{ $row->sku }}</small></td>@foreach($branches as $branch) @php($product=$row->branches[$branch->id]) <td class="p-4">@if($product)<span class="font-black {{ (float)$product->stock_quantity <= (float)$product->min_stock_level ? 'text-rose-400':'text-emerald-400' }}">{{ number_format((float)$product->stock_quantity,2,',','.') }}</span> <small class="text-slate-500">{{ $product->unit }}</small>@else<span class="text-slate-700">—</span>@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ $branches->count()+1 }}" class="p-8 text-center text-slate-500">Stok takibi yapılan ürün bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

<section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="font-black">Transferler</h2></div><div class="space-y-3 p-4">@forelse($transfers as $transfer)
<article class="rounded-xl border border-slate-800 bg-slate-950 p-4"><div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div class="flex items-center gap-2"><strong>{{ $transfer->transfer_number }}</strong><span class="rounded-full bg-slate-800 px-2 py-1 text-[10px] uppercase text-cyan-300">{{ ['requested'=>'Talep','approved'=>'Onaylandı','shipped'=>'Sevkte','received'=>'Teslim','cancelled'=>'İptal'][$transfer->status]??$transfer->status }}</span></div><p class="mt-1 text-sm text-slate-400">{{ $transfer->sourceBranch->name }} → {{ $transfer->targetBranch->name }}</p><p class="mt-1 text-xs text-slate-600">{{ $transfer->items->map(fn($i)=>$i->product_name.' ('.rtrim(rtrim(number_format((float)$i->quantity,3,'.',''),'0'),'.').' '.$i->unit.')')->join(', ') }}</p></div>@if($canTransfer)<div class="flex flex-wrap gap-2">@if($transfer->status==='requested')<form method="POST" action="{{ route('chain.stock-transfers.approve',$transfer) }}">@csrf<button class="rounded-lg bg-indigo-500 px-3 py-2 text-xs font-bold">Onayla</button></form>@endif @if($transfer->status==='approved')<form method="POST" action="{{ route('chain.stock-transfers.ship',$transfer) }}">@csrf<button class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-slate-950">Sevk Et</button></form>@endif @if($transfer->status==='shipped')<form method="POST" action="{{ route('chain.stock-transfers.receive',$transfer) }}">@csrf<button class="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950">Teslim Al</button></form>@endif @if(in_array($transfer->status,['requested','approved']))<form method="POST" action="{{ route('chain.stock-transfers.cancel',$transfer) }}" onsubmit="return confirm('Transfer iptal edilsin mi?')">@csrf<button class="rounded-lg border border-rose-500/30 px-3 py-2 text-xs text-rose-300">İptal</button></form>@endif</div>@endif</div></article>
@empty<p class="p-8 text-center text-sm text-slate-500">Henüz transfer yok.</p>@endforelse</div><div class="border-t border-slate-800 p-4">{{ $transfers->links() }}</div></section>
</div>
@if($canTransfer)<div id="transferModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4"><div class="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6"><div class="mb-5 flex justify-between"><h3 class="font-black">Yeni Stok Transferi</h3><button onclick="closeStockTransfer()">✕</button></div><form method="POST" action="{{ route('chain.stock-transfers.store') }}" class="space-y-4">@csrf<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-xs text-slate-400">Kaynak Şube</label><select id="sourceBranch" name="source_branch_id" required onchange="filterTransferProducts()" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs text-slate-400">Hedef Şube</label><select name="target_branch_id" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div></div><div><label class="mb-1 block text-xs text-slate-400">Ürün</label><select name="items[0][product_id]" id="transferProduct" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Önce kaynak şubeyi seçin</option>@foreach($products as $product)<option class="product-option" data-branch="{{ $product->branch_id }}" value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }} · Stok {{ $product->stock_quantity }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs text-slate-400">Miktar</label><input type="number" step="0.001" min="0.001" name="items[0][quantity]" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></div><div><label class="mb-1 block text-xs text-slate-400">Not</label><textarea name="notes" rows="2" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></textarea></div><button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Transfer Talebi Oluştur</button></form></div></div>@endif
<script>function openStockTransfer(){const e=document.getElementById('transferModal');e.classList.remove('hidden');e.classList.add('flex');filterTransferProducts()}function closeStockTransfer(){const e=document.getElementById('transferModal');e.classList.add('hidden');e.classList.remove('flex')}function filterTransferProducts(){const b=document.getElementById('sourceBranch')?.value;document.querySelectorAll('.product-option').forEach(o=>{o.hidden=!b||o.dataset.branch!==b});document.getElementById('transferProduct').value=''}</script>
@endsection
