@extends('chain.layout')
@section('title', 'Rapor Merkezi')
@section('content')
@php
    $modules = [
        'overview' => ['Genel Finans', 'M4 19V9m5 10V5m5 14v-7m5 7V3M2 21h20'],
        'tables' => ['Masalar', 'M4 21V10l8-6 8 6v11M8 21v-7h8v7M2 21h20'],
        'quick_sale' => ['Hızlı Satış', 'M13 2 5 9h-6l-1 11-5-9h6l1-11Z'],
        'delivery' => ['Paket Servis', 'M3 7h11v10H3V7Zm11 4h4l3 3v3h-7v-6ZM7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z'],
        'kitchen' => ['Mutfak', 'M4 3v7a4 4 0 0 0 8 0V3M8 3v18m8-18v18m0-9c3 0 4-2 4-5V3'],
        'products' => ['Ürünler', 'm4 7 8-4 8 4-8 4-8-4Zm0 0v10l8 4 8-4V7M12 11v10'],
        'stocks' => ['Stoklar', 'M21 8 12 3 3 8l9 5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5'],
        'purchasing' => ['Tedarik', 'M6 8V6a6 6 0 0 1 12 0v2m3 0H3l1 13h16L21 8'],
    ];
    $paymentLabels = ['nakit'=>'Nakit','kredi_karti'=>'Kredi Kartı','yemek_karti'=>'Yemek Kartı','online'=>'Çevrim İçi'];
    $channelLabels = ['trendyol'=>'Trendyol','yemeksepeti'=>'Yemeksepeti','getir'=>'Getir','migros'=>'Migros Yemek','phone'=>'Telefon'];
    $movementLabels = ['sale_deduction'=>'Satış Düşümü','cancellation_pending'=>'İptal Onayı','return_approved'=>'Stok İadesi','manual_addition'=>'Manuel Giriş','manual_subtraction'=>'Manuel Çıkış','purchase_receipt'=>'Mal Kabul','transfer_out'=>'Transfer Çıkışı','transfer_in'=>'Transfer Girişi','transfer_cancel_return'=>'Transfer İadesi'];
    $queryBase = ['start_date'=>$startDate->toDateString(),'end_date'=>$endDate->toDateString(),'branch_id'=>$selectedBranchId];
@endphp

<div class="mb-6 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
    <div><p class="institutional-page-kicker mb-1">Kurumsal Raporlama ve Analiz</p><h1>Yönetim Rapor Merkezi</h1><p class="mt-1 text-sm text-slate-400">Tüm POS modüllerinin şube ve dönem bazlı merkezi görünümü</p></div>
    <p class="text-xs text-slate-500">Rapor dönemi: <strong>{{ $startDate->format('d.m.Y') }} – {{ $endDate->format('d.m.Y') }}</strong></p>
</div>

<nav class="mb-5 grid grid-cols-2 gap-2 rounded-xl border border-slate-800 bg-slate-900 p-2 sm:grid-cols-4 xl:grid-cols-8" aria-label="Rapor modülleri">
    @foreach($modules as $key => [$label,$path])
    <a href="{{ route('chain.reports.index',array_filter($queryBase+['module'=>$key],fn($v)=>$v!==null&&$v!=='')) }}" class="flex min-h-16 flex-col items-center justify-center gap-1.5 rounded-lg border px-2 py-2 text-center text-xs font-semibold transition {{ $activeModule===$key?'border-cyan-500/30 bg-cyan-500/10 text-cyan-400':'border-transparent text-slate-500 hover:bg-slate-800' }}" @if($activeModule===$key) aria-current="page" @endif><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="{{ $path }}"/></svg><span>{{ $label }}</span></a>
    @endforeach
</nav>

<form method="GET" class="mb-6 grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-4">
    <input type="hidden" name="module" value="{{ $activeModule }}">
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Başlangıç Tarihi</label><input type="date" name="start_date" value="{{ $startDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Bitiş Tarihi</label><input type="date" name="end_date" value="{{ $endDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Şube Kapsamı</label><select name="branch_id" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Tüm Yetkili Şubeler</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId === $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
    <button class="institutional-action self-end rounded-lg bg-cyan-500 p-2.5 text-sm text-slate-950">Raporu Güncelle</button>
</form>

@if($activeModule==='overview')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
    @foreach([['Toplam Ciro','₺'.number_format((float)$summary->revenue,2,',','.')],['Adisyon',$summary->check_count],['Ortalama Sepet','₺'.number_format((float)$summary->average,2,',','.')],['İndirim','₺'.number_format((float)$summary->discounts,2,',','.')],['Tahmini Brüt Kâr','₺'.number_format((float)$summary->estimated_profit,2,',','.')],['Tahmini Marj',$summary->margin===null?'—':number_format((float)$summary->margin,1,',','.').'%']] as [$label,$value])
    <div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p>@if($label==='Toplam Ciro'&&$summary->revenue_change!==null)<small class="{{ $summary->revenue_change>=0?'text-emerald-400':'text-rose-400' }}">Önceki dönem: {{ $summary->revenue_change>=0?'+':'' }}{{ number_format($summary->revenue_change,1,',','.') }}%</small>@endif</div>
    @endforeach
</div>
@if($summary->missing_cost_products)<div class="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-400">{{ $summary->missing_cost_products }} ürünün satın alma maliyeti bulunmadığı için kâr hesabına dahil edilmedi.</div>@endif
<div class="mt-5 grid gap-5 xl:grid-cols-3">
    <section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900 xl:col-span-2"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Karşılaştırması</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Adisyon</th><th class="p-4">Misafir</th><th class="p-4">Ort. Sepet</th><th class="p-4">Ciro</th><th class="p-4">Tahmini Kâr</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($branches->whereIn('id',$selectedBranchId?[$selectedBranchId]:$branches->pluck('id')) as $branch) @php($sale=$salesByBranch->get($branch->id))<tr><td class="p-4 font-semibold">{{ $branch->name }}</td><td class="p-4">{{ $sale?->check_count??0 }}</td><td class="p-4">{{ $sale?->guests??0 }}</td><td class="p-4">₺{{ number_format((float)($sale?->average??0),2,',','.') }}</td><td class="p-4 font-semibold">₺{{ number_format((float)($sale?->revenue??0),2,',','.') }}</td><td class="p-4">₺{{ number_format((float)($sale?->estimated_profit??0),2,',','.') }}</td></tr>@endforeach</tbody></table></div></section>
    <section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Ödeme Dağılımı</h2></div><div class="space-y-2 p-4">@forelse($paymentBreakdown as $payment)<div class="flex justify-between border-b border-slate-800 py-2 text-sm"><span class="text-slate-500">{{ $paymentLabels[$payment->payment_method]??str_replace('_',' ',$payment->payment_method) }}</span><strong>₺{{ number_format((float)$payment->total,2,',','.') }}</strong></div>@empty<p class="py-8 text-center text-sm text-slate-500">Ödeme kaydı bulunamadı.</p>@endforelse</div></section>
</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 class="institutional-section-title mb-4">Günlük Satış Trendi</h2>@php($maxRevenue=max(1,(float)$dailySales->max('revenue'))) @forelse($dailySales as $day)<div class="mb-3"><div class="mb-1 flex justify-between text-xs"><span>{{ \Carbon\Carbon::parse($day->sale_date)->format('d.m.Y') }} · {{ $day->check_count }} adisyon</span><strong>₺{{ number_format((float)$day->revenue,2,',','.') }}</strong></div><div class="h-1.5 rounded-full bg-slate-800"><div class="h-1.5 rounded-full bg-cyan-500" style="width:{{ max(2,(float)$day->revenue/$maxRevenue*100) }}%"></div></div></div>@empty<p class="py-8 text-center text-sm text-slate-500">Satış kaydı bulunamadı.</p>@endforelse</section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">En Çok Satan Ürünler</h2></div>@include('chain.reports.partials.product-table',['products'=>$productPerformance->take(10)])</section></div>

@elseif($activeModule==='tables')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Toplam Masa',$tableSummary->total_tables],['Dolu Masa',$tableSummary->occupied],['Hesap Bekleyen',$tableSummary->awaiting_payment],['Boş Masa',$tableSummary->available],['Masa Adisyonu',$tableSummary->check_count],['Masa Cirosu','₺'.number_format((float)$tableSummary->revenue,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">En Yoğun Masalar</h2><p class="text-xs text-slate-500">Seçili dönemdeki ciroya göre sıralanmıştır</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Masa</th><th class="p-4">Adisyon</th><th class="p-4">Misafir</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($busiestTables as $row)<tr><td class="p-4">{{ $row->branch_name }}</td><td class="p-4 font-semibold">{{ $row->table_name }}</td><td class="p-4">{{ $row->check_count }}</td><td class="p-4">{{ $row->guests }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->revenue,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Masa satışı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

@elseif($activeModule==='quick_sale')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Satış Adedi',$quickSaleSummary->sale_count],['Toplam Ciro','₺'.number_format((float)$quickSaleSummary->revenue,2,',','.')],['Ortalama Sepet','₺'.number_format((float)$quickSaleSummary->average,2,',','.')],['Toplam İndirim','₺'.number_format((float)$quickSaleSummary->discounts,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Bazlı Hızlı Satış</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">İşlem</th><th class="p-4">Ortalama</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($branches->whereIn('id',$selectedBranchId?[$selectedBranchId]:$branches->pluck('id')) as $branch) @php($sale=$quickSalesByBranch->get($branch->id))<tr><td class="p-4 font-semibold">{{ $branch->name }}</td><td class="p-4">{{ $sale?->sale_count??0 }}</td><td class="p-4">₺{{ number_format((float)($sale?->average??0),2,',','.') }}</td><td class="p-4 font-semibold">₺{{ number_format((float)($sale?->revenue??0),2,',','.') }}</td></tr>@endforeach</tbody></table></section><section class="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 class="institutional-section-title mb-3">Ödeme Yöntemleri</h2>@forelse($quickPaymentBreakdown as $payment)<div class="flex justify-between border-b border-slate-800 py-3"><span>{{ $paymentLabels[$payment->payment_method]??$payment->payment_method }}</span><strong>₺{{ number_format((float)$payment->total,2,',','.') }}</strong></div>@empty<p class="py-8 text-center text-slate-500">Kayıt bulunamadı.</p>@endforelse</section></div>

@elseif($activeModule==='delivery')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Toplam Sipariş',$deliverySummary->order_count],['Teslim Edilen',$deliverySummary->delivered_count],['Aktif Sipariş',$deliverySummary->active_count],['İptal',$deliverySummary->cancelled_count],['Teslimat Cirosu','₺'.number_format((float)$deliverySummary->revenue,2,',','.')],['Ort. Teslim Süresi',$deliverySummary->average_minutes===null?'—':number_format($deliverySummary->average_minutes,1,',','.').' dk']] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Kanal Performansı</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Kanal</th><th class="p-4">Sipariş</th><th class="p-4">Teslim</th><th class="p-4">İptal</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($deliveryChannels as $row)<tr><td class="p-4 font-semibold">{{ $channelLabels[$row->channel]??ucfirst($row->channel) }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ $row->delivered_count }}</td><td class="p-4">{{ $row->cancelled_count }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->revenue,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Paket servis kaydı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

@elseif($activeModule==='kitchen')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Toplam Ürün',$kitchenSummary->item_count],['Bekleyen',$kitchenSummary->waiting_count],['Hazırlanan',$kitchenSummary->preparing_count],['Tamamlanan',$kitchenSummary->completed_count],['İptal',$kitchenSummary->cancelled_count]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p>@if($label==='Tamamlanan'&&$kitchenSummary->average_minutes!==null)<small class="text-slate-500">Ort. {{ number_format($kitchenSummary->average_minutes,1,',','.') }} dakika</small>@endif</div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Mutfakta En Çok İşlenen Ürünler</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Ürün</th><th class="p-4">Sipariş Sayısı</th><th class="p-4">Toplam Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($kitchenProducts as $row)<tr><td class="p-4 font-semibold">{{ $row->product_name }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ number_format((float)$row->quantity,2,',','.') }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Mutfak kaydı bulunamadı.</td></tr>@endforelse</tbody></table></section>

@elseif($activeModule==='products')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Satılan Ürün',$productPerformance->sum('quantity')],['Ürün Cirosu','₺'.number_format((float)$productPerformance->sum('revenue'),2,',','.')],['Tahmini Maliyet','₺'.number_format((float)$summary->estimated_cost,2,',','.')],['İptal Miktarı',number_format((float)$productExceptions->cancelled_quantity,2,',','.')],['İkram Değeri','₺'.number_format((float)$productExceptions->complimentary_value,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Ürün Satış ve Kârlılık Performansı</h2></div>@include('chain.reports.partials.product-table',['products'=>$productPerformance->take(30)])</section>

@elseif($activeModule==='stocks')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Takip Edilen Ürün',$stockSummary->product_count],['Kritik Stok',$stockSummary->low_stock],['Tükenen Ürün',$stockSummary->out_of_stock],['Toplam Stok Miktarı',number_format((float)$stockSummary->total_quantity,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Kritik Stok Listesi</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube / Ürün</th><th class="p-4">Mevcut</th><th class="p-4">Minimum</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($criticalStocks as $product)<tr><td class="p-4"><strong>{{ $product->name }}</strong><small class="block text-slate-500">{{ $product->branch?->name }} · {{ $product->sku }}</small></td><td class="p-4 text-rose-400">{{ number_format((float)$product->stock_quantity,2,',','.') }} {{ $product->unit }}</td><td class="p-4">{{ number_format((float)$product->min_stock_level,2,',','.') }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Kritik stok bulunmuyor.</td></tr>@endforelse</tbody></table></section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Stok Hareketleri</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Hareket</th><th class="p-4">İşlem</th><th class="p-4">Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($stockMovements as $row)<tr><td class="p-4 font-semibold">{{ $movementLabels[$row->type]??str_replace('_',' ',$row->type) }}</td><td class="p-4">{{ $row->movement_count }}</td><td class="p-4">{{ number_format((float)$row->quantity,2,',','.') }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Stok hareketi bulunamadı.</td></tr>@endforelse</tbody></table></section></div>

@elseif($activeModule==='purchasing')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Aktif Tedarikçi',$purchaseSummary->active_suppliers],['Sipariş',$purchaseSummary->order_count],['Açık Sipariş',$purchaseSummary->open_count],['Tamamlanan',$purchaseSummary->received_count],['Sipariş Tutarı','₺'.number_format((float)$purchaseSummary->ordered_value,2,',','.')],['Mal Kabul Tutarı','₺'.number_format((float)$purchaseSummary->received_value,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Tedarikçi Performansı</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Tedarikçi</th><th class="p-4">Şube</th><th class="p-4">Sipariş</th><th class="p-4">Tamamlanan</th><th class="p-4">Toplam Tutar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($supplierPerformance as $row)<tr><td class="p-4 font-semibold">{{ $row->supplier_name }}</td><td class="p-4">{{ $row->branch_name }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ $row->received_count }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->total,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Satın alma kaydı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>
@endif
@endsection
