@extends('chain.layout')
@section('title', 'Rapor Merkezi')
@section('content')
@php
    $modules = [
        'overview' => ['Genel Finans', 'M4 19V9m5 10V5m5 14v-7m5 7V3M2 21h20'],
        'tables' => ['Masalar', 'M4 21V10l8-6 8 6v11M8 21v-7h8v7M2 21h20'],
        'quick_sale' => ['Hızlı Satış', 'M13 2 5 9h-6l-1 11-5-9h6l1-11Z'],
        'delivery' => ['Paket Servis', 'M3 7h11v10H3V7Zm11 4h4l3 3v3h-7v-6ZM7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm11 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z'],
        'kitchen' => ['Mutfak', 'M4 3v7a4 4 0 0 0 8 0V3M8 3v18m8-18v18m0-9c3 0 4-2 4-5V3'],
        'products' => ['Ürünler', 'm4 7 8-4 8 4-8 4-8-4Zm0 0v10l8 4 8-4V7M12 11v10'],
        'stocks' => ['Stoklar', 'M21 8 12 3 3 8l9 5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5'],
        'production' => ['Üretim & Reçete', 'M9 3v2m6-2v2M5 8h14l-1 13H6L5 8Zm4 4h6m-7 4h8'],
        'purchasing' => ['Tedarik', 'M6 8V6a6 6 0 0 1 12 0v2m3 0H3l1 13h16L21 8'],
    ];
    $paymentLabels = ['nakit'=>'Nakit','kredi_karti'=>'Kredi Kartı','yemek_karti'=>'Yemek Kartı','online'=>'Çevrim İçi'];
    $channelLabels = ['trendyol'=>'Trendyol','yemeksepeti'=>'Yemeksepeti','getir'=>'Getir','migros'=>'Migros Yemek','phone'=>'Telefon'];
    $movementLabels = ['sale_deduction'=>'Satış Düşümü','cancellation_pending'=>'İptal Onayı','return_approved'=>'Stok İadesi','manual_addition'=>'Manuel Giriş','manual_subtraction'=>'Manuel Çıkış','purchase_receipt'=>'Mal Kabul','transfer_out'=>'Transfer Çıkışı','transfer_in'=>'Transfer Girişi','transfer_cancel_return'=>'Transfer İadesi','central_distribution'=>'Merkezden Dağıtım','workflow_consumption'=>'Üretim Tüketimi','workflow_output'=>'Mamul Girişi','central_addition'=>'Merkez Giriş','central_subtraction'=>'Merkez Çıkış','stock_count'=>'Sayım Düzeltmesi','distribution_out'=>'Şubeye Dağıtım'];
    $workflowStatusLabels=['planned'=>'Planlandı','in_progress'=>'Üretimde','completed'=>'Tamamlandı','cancelled'=>'İptal'];
    $workflowStatusClasses=['planned'=>'text-blue-500','in_progress'=>'text-amber-500','completed'=>'text-emerald-500','cancelled'=>'text-rose-500'];
    $queryBase = ['start_date'=>$startDate->toDateString(),'end_date'=>$endDate->toDateString(),'branch_id'=>$selectedBranchId];
    $reportChartMax=max(1,(float)$dailySales->max('revenue')); $reportChartCount=max(1,$dailySales->count()-1); $reportLabelEvery=max(1,(int)ceil(max(1,$dailySales->count())/7));
    $reportChartPoints=$dailySales->values()->map(fn($day,$i)=>(30+$i*(639/$reportChartCount)).','.(190-((float)$day->revenue/$reportChartMax*145)))->join(' ');
    $reportAreaPoints=$dailySales->isEmpty()?'30,190 669,190':'30,190 '.$reportChartPoints.' 669,190';
    $reportPaymentTotal=max(1,(float)$paymentBreakdown->sum('total')); $reportPaymentColors=['#174a75','#2675ad','#42a0cf','#75bddb']; $reportDonutParts=[]; $reportCursor=0;
    foreach($paymentBreakdown as $i=>$payment){$partStart=$reportCursor;$reportCursor+=(float)$payment->total/$reportPaymentTotal*100;$reportDonutParts[]=($reportPaymentColors[$i%count($reportPaymentColors)]).' '.$partStart.'% '.$reportCursor.'%';}
    $reportDonutStyle=$reportDonutParts?implode(',',$reportDonutParts):'#dbe2ea 0% 100%';
@endphp

<div class="mb-6 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
    <div><p class="institutional-page-kicker mb-1">Kurumsal Raporlama ve Analiz</p><h1>Yönetim Rapor Merkezi</h1><p class="mt-1 text-sm text-slate-400">Tüm POS modüllerinin şube ve dönem bazlı merkezi görünümü</p></div>
    <p class="text-xs text-slate-500">Rapor dönemi: <strong>{{ $startDate->format('d.m.Y') }} – {{ $endDate->format('d.m.Y') }}</strong></p>
</div>

<nav class="mb-5 grid grid-cols-2 gap-2 rounded-xl border border-slate-800 bg-slate-900 p-2 sm:grid-cols-3 xl:grid-cols-9" aria-label="Rapor modülleri">
    @foreach($modules as $key => [$label,$path])
    <a href="{{ route('chain.reports.index',array_filter($queryBase+['module'=>$key],fn($v)=>$v!==null&&$v!=='')) }}" class="flex min-h-16 flex-col items-center justify-center gap-1.5 rounded-lg border px-2 py-2 text-center text-xs font-semibold transition {{ $activeModule===$key?'border-cyan-500/30 bg-cyan-500/10 text-cyan-400':'border-transparent text-slate-500 hover:bg-slate-800' }}" @if($activeModule===$key) aria-current="page" @endif><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="{{ $path }}"/></svg><span>{{ $label }}</span></a>
    @endforeach
</nav>

<form method="GET" class="mb-6 grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-4">
    <input type="hidden" name="module" value="{{ $activeModule }}">
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Başlangıç Tarihi</label><input type="date" name="start_date" value="{{ $startDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Bitiş Tarihi</label><input type="date" name="end_date" value="{{ $endDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs font-medium text-slate-500">Şube Kapsamı</label><select name="branch_id" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Tüm Yetkili Şubeler</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId === $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
    <button class="institutional-action self-end rounded-lg bg-cyan-500 p-2.5 text-sm text-slate-950">Raporu Güncelle</button>
</form>

@if($activeModule==='overview')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
    @foreach([['Toplam Ciro','₺'.number_format((float)$summary->revenue,2,',','.')],['Adisyon',$summary->check_count],['Ortalama Sepet','₺'.number_format((float)$summary->average,2,',','.')],['İndirim','₺'.number_format((float)$summary->discounts,2,',','.')],['Tahmini Brüt Kâr','₺'.number_format((float)$summary->estimated_profit,2,',','.')],['Tahmini Marj',$summary->margin===null?'—':number_format((float)$summary->margin,1,',','.').'%']] as [$label,$value])
    <div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p>@if($label==='Toplam Ciro'&&$summary->revenue_change!==null)<small class="{{ $summary->revenue_change>=0?'text-emerald-400':'text-rose-400' }}">Önceki dönem: {{ $summary->revenue_change>=0?'+':'' }}{{ number_format($summary->revenue_change,1,',','.') }}%</small>@endif</div>
    @endforeach
</div>
<div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    @foreach([['Merkezi Hammadde',$centralStockSummary->product_count,'Merkez depo'],['Merkez Kritik',$centralStockSummary->critical_count,'Minimum ve tükenen'],['Aktif Reçete',$productionSummary->active_recipes,'Seçili şubeler'],['Açık Üretim',(int)$productionSummary->planned_count+(int)$productionSummary->in_progress_count,'Planlanan + üretimde']] as [$label,$value,$hint])
    <div class="rounded-xl border border-slate-800 bg-slate-900 px-4 py-3"><div class="flex items-center justify-between"><span class="text-xs font-semibold text-slate-500">{{ $label }}</span><strong class="text-lg">{{ $value }}</strong></div><small class="text-slate-600">{{ $hint }}</small></div>
    @endforeach
</div>
@if($summary->missing_cost_products)<div class="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-400">{{ $summary->missing_cost_products }} ürünün satın alma maliyeti bulunmadığı için kâr hesabına dahil edilmedi.</div>@endif
<div class="mt-5 grid gap-5 xl:grid-cols-3">
    <section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900 xl:col-span-2"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Karşılaştırması</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Adisyon</th><th class="p-4">Misafir</th><th class="p-4">Ort. Sepet</th><th class="p-4">Ciro</th><th class="p-4">Tahmini Kâr</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($branches->whereIn('id',$selectedBranchId?[$selectedBranchId]:$branches->pluck('id')) as $branch) @php($sale=$salesByBranch->get($branch->id))<tr><td class="p-4 font-semibold">{{ $branch->name }}</td><td class="p-4">{{ $sale?->check_count??0 }}</td><td class="p-4">{{ $sale?->guests??0 }}</td><td class="p-4">₺{{ number_format((float)($sale?->average??0),2,',','.') }}</td><td class="p-4 font-semibold">₺{{ number_format((float)($sale?->revenue??0),2,',','.') }}</td><td class="p-4">₺{{ number_format((float)($sale?->estimated_profit??0),2,',','.') }}</td></tr>@endforeach</tbody></table></div></section>
    <section class="executive-panel overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Ödeme Dağılımı</h2><p class="text-xs text-slate-500">Seçili dönemin tahsilat kanalları</p></div><div class="flex flex-col items-center p-5"><div class="executive-donut" style="background:conic-gradient({{ $reportDonutStyle }})"><div><strong>₺{{ number_format((float)$paymentBreakdown->sum('total'),0,',','.') }}</strong><span>Toplam</span></div></div><div class="mt-5 w-full space-y-3">@forelse($paymentBreakdown as $i=>$payment)<div class="flex items-center justify-between text-xs"><span class="flex items-center gap-2 text-slate-500"><i style="background:{{ $reportPaymentColors[$i%count($reportPaymentColors)] }}"></i>{{ $paymentLabels[$payment->payment_method]??str_replace('_',' ',$payment->payment_method) }}</span><strong>%{{ number_format((float)$payment->total/$reportPaymentTotal*100,1,',','.') }}</strong></div>@empty<p class="py-6 text-center text-sm text-slate-500">Ödeme kaydı bulunamadı.</p>@endforelse</div></div></section>
</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="executive-panel overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 class="institutional-section-title">Günlük Satış Grafiği</h2><p class="text-xs text-slate-500">Filtrelenen dönemin ciro hareketi</p></div><strong>₺{{ number_format((float)$dailySales->sum('revenue'),2,',','.') }}</strong></div><div class="p-4"><svg class="executive-line-chart w-full" viewBox="0 0 700 235" role="img" aria-label="Filtrelenen dönem satış grafiği"><defs><linearGradient id="reportSalesArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#2675ad" stop-opacity=".32"/><stop offset="100%" stop-color="#2675ad" stop-opacity=".02"/></linearGradient></defs><g class="chart-grid"><line x1="30" y1="45" x2="669" y2="45"/><line x1="30" y1="93" x2="669" y2="93"/><line x1="30" y1="141" x2="669" y2="141"/><line x1="30" y1="190" x2="669" y2="190"/></g><polygon points="{{ $reportAreaPoints }}" fill="url(#reportSalesArea)"/><polyline points="{{ $reportChartPoints }}" class="chart-line"/>@foreach($dailySales->values() as $i=>$day) @php($rx=30+$i*(639/$reportChartCount)) @php($ry=190-((float)$day->revenue/$reportChartMax*145))<circle cx="{{ $rx }}" cy="{{ $ry }}" r="4" class="chart-point"><title>{{ \Carbon\Carbon::parse($day->sale_date)->format('d.m.Y') }}: ₺{{ number_format((float)$day->revenue,2,',','.') }}</title></circle>@if($i%$reportLabelEvery===0||$i===$dailySales->count()-1)<text x="{{ $rx }}" y="218" text-anchor="middle" class="chart-label">{{ \Carbon\Carbon::parse($day->sale_date)->format('d.m') }}</text>@endif @endforeach</svg></div></section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">En Çok Satan Ürünler</h2></div>@include('chain.reports.partials.product-table',['products'=>$productPerformance->take(10)])</section></div>

@elseif($activeModule==='tables')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Toplam Masa',$tableSummary->total_tables],['Dolu Masa',$tableSummary->occupied],['Hesap Bekleyen',$tableSummary->awaiting_payment],['Boş Masa',$tableSummary->available],['Masa Adisyonu',$tableSummary->check_count],['Masa Cirosu','₺'.number_format((float)$tableSummary->revenue,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">En Yoğun Masalar</h2><p class="text-xs text-slate-500">Seçili dönemdeki ciroya göre sıralanmıştır</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Masa</th><th class="p-4">Adisyon</th><th class="p-4">Misafir</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($busiestTables as $row)<tr><td class="p-4">{{ $row->branch_name }}</td><td class="p-4 font-semibold">{{ $row->table_name }}</td><td class="p-4">{{ $row->check_count }}</td><td class="p-4">{{ $row->guests }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->revenue,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Masa satışı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

@elseif($activeModule==='quick_sale')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Satış Adedi',$quickSaleSummary->sale_count],['Toplam Ciro','₺'.number_format((float)$quickSaleSummary->revenue,2,',','.')],['Ortalama Sepet','₺'.number_format((float)$quickSaleSummary->average,2,',','.')],['Toplam İndirim','₺'.number_format((float)$quickSaleSummary->discounts,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Bazlı Hızlı Satış</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">İşlem</th><th class="p-4">Ortalama</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($branches->whereIn('id',$selectedBranchId?[$selectedBranchId]:$branches->pluck('id')) as $branch) @php($sale=$quickSalesByBranch->get($branch->id))<tr><td class="p-4 font-semibold">{{ $branch->name }}</td><td class="p-4">{{ $sale?->sale_count??0 }}</td><td class="p-4">₺{{ number_format((float)($sale?->average??0),2,',','.') }}</td><td class="p-4 font-semibold">₺{{ number_format((float)($sale?->revenue??0),2,',','.') }}</td></tr>@endforeach</tbody></table></section><section class="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 class="institutional-section-title mb-3">Ödeme Yöntemleri</h2>@forelse($quickPaymentBreakdown as $payment)<div class="flex justify-between border-b border-slate-800 py-3"><span>{{ $paymentLabels[$payment->payment_method]??$payment->payment_method }}</span><strong>₺{{ number_format((float)$payment->total,2,',','.') }}</strong></div>@empty<p class="py-8 text-center text-slate-500">Kayıt bulunamadı.</p>@endforelse</section></div>

@elseif($activeModule==='delivery')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Toplam Sipariş',$deliverySummary->order_count],['Teslim Edilen',$deliverySummary->delivered_count],['Aktif Sipariş',$deliverySummary->active_count],['İptal',$deliverySummary->cancelled_count],['Teslimat Cirosu','₺'.number_format((float)$deliverySummary->revenue,2,',','.')],['Ort. Teslim Süresi',$deliverySummary->average_minutes===null?'—':number_format($deliverySummary->average_minutes,1,',','.').' dk']] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Kanal Performansı</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Kanal</th><th class="p-4">Sipariş</th><th class="p-4">Teslim</th><th class="p-4">İptal</th><th class="p-4">Ciro</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($deliveryChannels as $row)<tr><td class="p-4 font-semibold">{{ $channelLabels[$row->channel]??ucfirst($row->channel) }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ $row->delivered_count }}</td><td class="p-4">{{ $row->cancelled_count }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->revenue,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Paket servis kaydı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>

@elseif($activeModule==='kitchen')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Toplam Ürün',$kitchenSummary->item_count],['Bekleyen',$kitchenSummary->waiting_count],['Hazırlanan',$kitchenSummary->preparing_count],['Tamamlanan',$kitchenSummary->completed_count],['İptal',$kitchenSummary->cancelled_count]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p>@if($label==='Tamamlanan'&&$kitchenSummary->average_minutes!==null)<small class="text-slate-500">Ort. {{ number_format($kitchenSummary->average_minutes,1,',','.') }} dakika</small>@endif</div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Mutfakta En Çok İşlenen Ürünler</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Ürün</th><th class="p-4">Sipariş Sayısı</th><th class="p-4">Toplam Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($kitchenProducts as $row)<tr><td class="p-4 font-semibold">{{ $row->product_name }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ number_format((float)$row->quantity,2,',','.') }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Mutfak kaydı bulunamadı.</td></tr>@endforelse</tbody></table></section>

@elseif($activeModule==='products')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Satılan Ürün',$productPerformance->sum('quantity')],['Ürün Cirosu','₺'.number_format((float)$productPerformance->sum('revenue'),2,',','.')],['Tahmini Maliyet','₺'.number_format((float)$summary->estimated_cost,2,',','.')],['İptal Miktarı',number_format((float)$productExceptions->cancelled_quantity,2,',','.')],['İkram Değeri','₺'.number_format((float)$productExceptions->complimentary_value,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Ürün Satış ve Kârlılık Performansı</h2></div>@include('chain.reports.partials.product-table',['products'=>$productPerformance->take(30)])</section>

@elseif($activeModule==='stocks')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Merkezi Hammadde',$centralStockSummary->product_count],['Merkez Kritik',$centralStockSummary->critical_count],['Merkez Tükenen',$centralStockSummary->out_of_stock],['Şube Takipli',$stockSummary->product_count],['Şube Kritik',(int)$stockSummary->low_stock+(int)$stockSummary->out_of_stock],['Dönem Merkez Hareketi',$centralStockMovements->sum('movement_count')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 rounded-xl border border-slate-800 bg-slate-900 p-4"><div class="mb-3"><h2 class="institutional-section-title">Merkez Depo Birim Bakiyeleri</h2><p class="text-xs text-slate-500">Kg, litre ve adet birbirine eklenmeden ayrı raporlanır.</p></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@forelse($centralUnitTotals as $row)<div class="rounded-lg border border-slate-800 bg-slate-950 p-4"><p class="text-xs uppercase text-slate-500">{{ $row->unit }} · {{ $row->product_count }} ürün</p><strong class="mt-1 block text-2xl text-cyan-400">{{ number_format((float)$row->stock_quantity,3,',','.') }} {{ $row->unit }}</strong></div>@empty<p class="text-sm text-slate-500">Merkezi stok kaydı bulunamadı.</p>@endforelse</div></section>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Merkez Depo Kritik Listesi</h2></div><div class="max-h-96 overflow-auto"><table class="w-full text-sm"><thead class="sticky top-0 bg-slate-950 text-left text-xs text-slate-500"><tr><th class="p-4">Hammadde</th><th class="p-4">Mevcut</th><th class="p-4">Minimum</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($centralCriticalStocks as $product)<tr><td class="p-4"><strong>{{ $product->name }}</strong><small class="block text-slate-500">{{ $product->category?->name }} · {{ $product->sku }}</small></td><td class="p-4 text-rose-400">{{ number_format((float)$product->stock_quantity,3,',','.') }} {{ $product->unit }}</td><td class="p-4">{{ number_format((float)$product->min_stock_level,3,',','.') }} {{ $product->unit }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Merkez depoda kritik stok bulunmuyor.</td></tr>@endforelse</tbody></table></div></section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Kritik Stokları</h2></div><div class="max-h-96 overflow-auto"><table class="w-full text-sm"><thead class="sticky top-0 bg-slate-950 text-left text-xs text-slate-500"><tr><th class="p-4">Şube / Ürün</th><th class="p-4">Mevcut</th><th class="p-4">Minimum</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($criticalStocks as $product)<tr><td class="p-4"><strong>{{ $product->name }}</strong><small class="block text-slate-500">{{ $product->branch?->name }} · {{ $product->sku }}</small></td><td class="p-4 text-rose-400">{{ number_format((float)$product->stock_quantity,2,',','.') }} {{ $product->unit }}</td><td class="p-4">{{ number_format((float)$product->min_stock_level,2,',','.') }} {{ $product->unit }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Şubelerde kritik stok bulunmuyor.</td></tr>@endforelse</tbody></table></div></section></div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Merkez Depo Hareketleri</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Hareket</th><th class="p-4">İşlem</th><th class="p-4">Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($centralStockMovements as $row)<tr><td class="p-4 font-semibold">{{ $movementLabels[$row->type]??str_replace('_',' ',$row->type) }}</td><td class="p-4">{{ $row->movement_count }}</td><td class="p-4">{{ number_format((float)$row->quantity,3,',','.') }} {{ $row->unit }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Merkez depo hareketi bulunamadı.</td></tr>@endforelse</tbody></table></section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Şube Stok Hareketleri</h2></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Hareket</th><th class="p-4">İşlem</th><th class="p-4">Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($stockMovements as $row)<tr><td class="p-4 font-semibold">{{ $movementLabels[$row->type]??str_replace('_',' ',$row->type) }}</td><td class="p-4">{{ $row->movement_count }}</td><td class="p-4">{{ number_format((float)$row->quantity,2,',','.') }}</td></tr>@empty<tr><td colspan="3" class="p-10 text-center text-slate-500">Şube stok hareketi bulunamadı.</td></tr>@endforelse</tbody></table></section></div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Merkezden Şubelere Dağıtım</h2><p class="text-xs text-slate-500">Seçili tarih ve şube kapsamındaki dağıtımlar</p></div><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Birim</th><th class="p-4">Dağıtım İşlemi</th><th class="p-4">Toplam Miktar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($centralDistributionByBranch as $row)<tr><td class="p-4 font-semibold">{{ $row->branch_name }}</td><td class="p-4">{{ $row->unit }}</td><td class="p-4">{{ $row->movement_count }}</td><td class="p-4 font-semibold">{{ number_format((float)$row->quantity,3,',','.') }} {{ $row->unit }}</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-500">Seçili dönemde şube dağıtımı bulunamadı.</td></tr>@endforelse</tbody></table></section>

@elseif($activeModule==='production')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Aktif Reçete',$productionSummary->active_recipes],['Dönem İş Emri',$productionSummary->workflow_count],['Planlanan',$productionSummary->planned_count],['Üretimde',$productionSummary->in_progress_count],['Tamamlanan',$productionSummary->completed_count],['Üretilen Porsiyon',number_format((float)$productionSummary->completed_servings,0,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="rounded-xl border border-slate-800 bg-slate-900 p-4"><div class="mb-4"><h2 class="institutional-section-title">Üretim ve Reçete Performansı</h2><p class="text-xs text-slate-500">Tamamlanan iş emirlerinin porsiyon dağılımı</p></div>@php($productionOutputMax=max(1,(float)$productionOutputs->max('servings')))@forelse($productionOutputs as $row)<div class="mb-4"><div class="mb-1 flex items-center justify-between gap-3 text-xs"><span><strong>{{ $row->recipe_name }}</strong><small class="ml-1 text-slate-500">{{ $row->branch_name }}</small></span><strong>{{ number_format((float)$row->servings,0,',','.') }} porsiyon</strong></div><div class="h-2 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full bg-cyan-500" style="width:{{ max(3,(float)$row->servings/$productionOutputMax*100) }}%"></div></div></div>@empty<p class="py-10 text-center text-sm text-slate-500">Seçili dönemde tamamlanan üretim bulunamadı.</p>@endforelse</section><section class="rounded-xl border border-slate-800 bg-slate-900 p-4"><div class="mb-4"><h2 class="institutional-section-title">Tüketilen Hammadde</h2><p class="text-xs text-slate-500">Tamamlanan üretimlerin birim bazlı toplamı</p></div><div class="grid gap-3 sm:grid-cols-2">@forelse($productionConsumptionByUnit as $row)<div class="rounded-lg border border-slate-800 bg-slate-950 p-4"><p class="text-xs uppercase text-slate-500">{{ $row->unit }}</p><strong class="mt-1 block text-2xl text-amber-400">{{ number_format((float)$row->quantity,3,',','.') }} {{ $row->unit }}</strong></div>@empty<p class="text-sm text-slate-500">Tüketim kaydı bulunamadı.</p>@endforelse</div></section></div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Aktif Reçeteler</h2></div><div class="max-h-96 overflow-auto"><table class="w-full text-sm"><thead class="sticky top-0 bg-slate-950 text-left text-xs text-slate-500"><tr><th class="p-4">Şube / Reçete</th><th class="p-4">Çıktı</th><th class="p-4">Baz</th><th class="p-4">Malzeme</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($activeRecipes as $recipe)<tr><td class="p-4"><strong>{{ $recipe->name }}</strong><small class="block text-slate-500">{{ $recipe->branch?->name }}</small></td><td class="p-4">{{ $recipe->outputProduct?->name??'—' }}</td><td class="p-4">{{ number_format((float)$recipe->base_servings,0,',','.') }}</td><td class="p-4">{{ $recipe->items_count }}</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-500">Aktif reçete bulunamadı.</td></tr>@endforelse</tbody></table></div></section><section class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Son Üretim İş Emirleri</h2></div><div class="max-h-96 overflow-auto"><table class="w-full text-sm"><thead class="sticky top-0 bg-slate-950 text-left text-xs text-slate-500"><tr><th class="p-4">İş Emri</th><th class="p-4">Şube</th><th class="p-4">Porsiyon</th><th class="p-4">Durum</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($recentWorkflows as $workflow)<tr><td class="p-4"><strong>{{ $workflow->recipe_name }}</strong><small class="block font-mono text-slate-500">{{ $workflow->workflow_number }}</small></td><td class="p-4">{{ $workflow->branch?->name }}</td><td class="p-4">{{ number_format((float)$workflow->planned_servings,0,',','.') }}</td><td class="p-4 font-semibold {{ $workflowStatusClasses[$workflow->status]??'text-slate-400' }}">{{ $workflowStatusLabels[$workflow->status]??$workflow->status }}</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-500">Seçili dönemde iş emri bulunamadı.</td></tr>@endforelse</tbody></table></div></section></div>

@elseif($activeModule==='purchasing')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Aktif Tedarikçi',$purchaseSummary->active_suppliers],['Sipariş',$purchaseSummary->order_count],['Açık Sipariş',$purchaseSummary->open_count],['Tamamlanan',$purchaseSummary->received_count],['Sipariş Tutarı','₺'.number_format((float)$purchaseSummary->ordered_value,2,',','.')],['Mal Kabul Tutarı','₺'.number_format((float)$purchaseSummary->received_value,2,',','.')]] as [$label,$value])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold">{{ $value }}</p></div>@endforeach</div>
<section class="mt-5 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 p-4"><h2 class="institutional-section-title">Tedarikçi Performansı</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs text-slate-500"><tr><th class="p-4">Tedarikçi</th><th class="p-4">Şube</th><th class="p-4">Sipariş</th><th class="p-4">Tamamlanan</th><th class="p-4">Toplam Tutar</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($supplierPerformance as $row)<tr><td class="p-4 font-semibold">{{ $row->supplier_name }}</td><td class="p-4">{{ $row->branch_name }}</td><td class="p-4">{{ $row->order_count }}</td><td class="p-4">{{ $row->received_count }}</td><td class="p-4 font-semibold">₺{{ number_format((float)$row->total,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Satın alma kaydı bulunamadı.</td></tr>@endforelse</tbody></table></div></section>
@endif
@endsection
