@extends('chain.layout')
@section('title', 'Gelişmiş Raporlar')
@section('content')
<div class="mb-6"><p class="institutional-page-kicker mb-1">Raporlama ve Analiz</p><h1>Zincir Performans Raporu</h1><p class="mt-1 text-sm text-slate-400">Satış, şube performansı ve tahmini kârlılık göstergeleri</p></div>

<form method="GET" class="mb-6 grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-4">
    <div><label class="mb-1 block text-xs text-slate-500">Başlangıç</label><input type="date" name="start_date" value="{{ $startDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs text-slate-500">Bitiş</label><input type="date" name="end_date" value="{{ $endDate->toDateString() }}" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></div>
    <div><label class="mb-1 block text-xs text-slate-500">Şube</label><select name="branch_id" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Tüm erişilebilir şubeler</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId === $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
    <button class="institutional-action self-end rounded-lg bg-cyan-500 p-2.5 text-sm text-slate-950">Raporu Görüntüle</button>
</form>

<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
    @foreach([['Ciro','₺'.number_format((float)$summary->revenue,2,',','.'),'text-emerald-400'],['Adisyon',$summary->check_count,'text-white'],['Ortalama Sepet','₺'.number_format((float)$summary->average,2,',','.'),'text-cyan-400'],['İndirim','₺'.number_format((float)$summary->discounts,2,',','.'),'text-amber-400'],['Tahmini Brüt Kâr','₺'.number_format((float)$summary->estimated_profit,2,',','.'),'text-indigo-400'],['Tahmini Marj',$summary->margin===null?'—':number_format((float)$summary->margin,1,',','.').'%','text-fuchsia-400']] as [$label,$value,$color])
    <div class="institutional-metric rounded-2xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-2xl font-semibold {{ $color }}">{{ $value }}</p>@if($label==='Ciro' && $summary->revenue_change!==null)<small class="{{ $summary->revenue_change>=0?'text-emerald-400':'text-rose-400' }}">Önceki döneme göre {{ $summary->revenue_change>=0?'+':'' }}{{ number_format($summary->revenue_change,1,',','.') }}%</small>@endif</div>
    @endforeach
</div>
@if($summary->missing_cost_products)<p class="mt-3 text-xs text-amber-400">{{ $summary->missing_cost_products }} ürünün satın alma maliyeti bulunmadığı için kâr hesabına dahil edilmedi.</p>@endif

<div class="mt-6 grid gap-6 xl:grid-cols-3">
    <section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 xl:col-span-2"><h2 class="border-b border-slate-800 p-4 font-black">Şube Karşılaştırması</h2><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Şube</th><th class="p-4">Adisyon</th><th class="p-4">Misafir</th><th class="p-4">Ort. Sepet</th><th class="p-4">Ciro</th><th class="p-4">Tahmini Kâr</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($branches->whereIn('id', $selectedBranchId ? [$selectedBranchId] : $branches->pluck('id')) as $branch) @php($sale=$salesByBranch->get($branch->id)) <tr><td class="p-4 font-bold">{{ $branch->name }}</td><td class="p-4">{{ $sale?->check_count ?? 0 }}</td><td class="p-4">{{ $sale?->guests ?? 0 }}</td><td class="p-4">₺{{ number_format((float)($sale?->average ?? 0),2,',','.') }}</td><td class="p-4 font-bold text-emerald-400">₺{{ number_format((float)($sale?->revenue ?? 0),2,',','.') }}</td><td class="p-4 font-bold text-indigo-400">₺{{ number_format((float)($sale?->estimated_profit ?? 0),2,',','.') }}</td></tr>@endforeach</tbody></table></div></section>
    <section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 class="border-b border-slate-800 p-4 font-black">Ödeme Dağılımı</h2><div class="space-y-3 p-4">@forelse($paymentBreakdown as $payment)<div class="flex justify-between rounded-xl bg-slate-950 p-3"><span class="capitalize text-slate-400">{{ str_replace('_',' ',$payment->payment_method) }}</span><strong>₺{{ number_format((float)$payment->total,2,',','.') }}</strong></div>@empty<p class="text-sm text-slate-500">Bu aralıkta ödeme yok.</p>@endforelse</div></section>
</div>

<div class="mt-6 grid gap-6 xl:grid-cols-2">
    <section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 class="border-b border-slate-800 p-4 font-black">Günlük Satış Trendi</h2><div class="space-y-3 p-4">@php($maxRevenue=max(1,(float)$dailySales->max('revenue'))) @forelse($dailySales as $day)<div><div class="mb-1 flex justify-between text-xs"><span>{{ \Carbon\Carbon::parse($day->sale_date)->format('d.m.Y') }} · {{ $day->check_count }} adisyon</span><strong>₺{{ number_format((float)$day->revenue,2,',','.') }}</strong></div><div class="h-2 rounded-full bg-slate-800"><div class="h-2 rounded-full bg-cyan-500" style="width:{{ max(2,(float)$day->revenue/$maxRevenue*100) }}%"></div></div></div>@empty<p class="text-sm text-slate-500">Kayıt bulunamadı.</p>@endforelse</div></section>
    <section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 class="border-b border-slate-800 p-4 font-black">En Çok Satan Ürünler</h2><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Ürün</th><th class="p-4">Adet</th><th class="p-4">Ciro</th><th class="p-4">Tahmini Kâr</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($productPerformance->take(10) as $product)<tr><td class="p-4 font-bold">{{ $product->product_name }}</td><td class="p-4">{{ number_format((float)$product->quantity,2,',','.') }}</td><td class="p-4 text-emerald-400">₺{{ number_format((float)$product->revenue,2,',','.') }}</td><td class="p-4 {{ $product->estimated_profit===null?'text-slate-600':'text-indigo-400' }}">{{ $product->estimated_profit===null?'Maliyet yok':'₺'.number_format((float)$product->estimated_profit,2,',','.') }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Satış verisi bulunamadı.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
