@extends('chain.layout')
@section('title','Merkezi Satın Alma')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div><h1 class="text-3xl font-black">Merkezi Satın Alma</h1><p class="mt-1 text-sm text-slate-400">Tedarikçileri, siparişleri ve şube mal kabullerini tek noktadan yönetin.</p></div>
        @if($canManage)<div class="flex gap-2"><button onclick="toggleModal('supplierModal',true)" class="rounded-xl border border-cyan-500/30 px-4 py-2.5 text-sm font-bold text-cyan-300">Tedarikçi Ekle</button><button onclick="toggleModal('orderModal',true)" class="rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-black text-slate-950">Yeni Sipariş</button></div>@endif
    </div>
    @if(session('success'))<div class="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{{ $errors->first() }}</div>@endif

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p class="text-xs uppercase text-slate-500">Aktif Tedarikçi</p><p class="mt-2 text-3xl font-black">{{ $stats['suppliers'] }}</p></div>
        <div class="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p class="text-xs uppercase text-slate-500">Açık Sipariş</p><p class="mt-2 text-3xl font-black">{{ $stats['open'] }}</p></div>
        <div class="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p class="text-xs uppercase text-slate-500">Bekleyen Tutar</p><p class="mt-2 text-3xl font-black text-amber-400">₺{{ number_format((float)$stats['pending'],2,',','.') }}</p></div>
        <div class="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p class="text-xs uppercase text-slate-500">Tamamlanan</p><p class="mt-2 text-3xl font-black text-emerald-400">₺{{ number_format((float)$stats['received'],2,',','.') }}</p></div>
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">
        <div class="border-b border-slate-800 p-4"><h2 class="font-black">Satın Alma Siparişleri</h2></div>
        <div class="space-y-3 p-4">@forelse($orders as $order)
            @php($labels=['draft'=>'Taslak','ordered'=>'Sipariş Verildi','partial'=>'Kısmi Teslim','received'=>'Tamamlandı','cancelled'=>'İptal'])
            <article class="rounded-xl border border-slate-800 bg-slate-950 p-4">
                <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
                    <div><div class="flex flex-wrap items-center gap-2"><strong>{{ $order->order_number }}</strong><span class="rounded-full bg-slate-800 px-2 py-1 text-[10px] uppercase text-cyan-300">{{ $labels[$order->status] ?? $order->status }}</span></div><p class="mt-1 text-sm text-slate-400">{{ $order->branch->name }} · {{ $order->supplier->name }} · ₺{{ number_format((float)$order->total,2,',','.') }}</p><p class="mt-1 text-xs text-slate-600">{{ $order->items->map(fn($item) => $item->product_name.' ('.(float)$item->quantity.' '.$item->unit.')')->join(', ') }}</p></div>
                    @if($canManage)<div class="flex flex-wrap gap-2">
                        @if($order->status==='draft')<form method="POST" action="{{ route('chain.purchasing.orders.place',$order->id) }}">@csrf<button class="rounded-lg bg-indigo-500 px-3 py-2 text-xs font-bold">Onayla</button></form>@endif
                        @if(in_array($order->status,['ordered','partial']))<form method="POST" action="{{ route('chain.purchasing.orders.receive',$order->id) }}" class="flex gap-2">@csrf @foreach($order->items as $item)<input type="number" step="0.001" min="0" max="{{ (float)$item->quantity-(float)$item->received_quantity }}" name="quantities[{{ $item->id }}]" placeholder="{{ $item->product_name }}" class="w-32 rounded-lg border border-slate-700 bg-slate-900 px-2 text-xs">@endforeach<button class="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950">Mal Kabul</button></form>@endif
                        @if(in_array($order->status,['draft','ordered']))<form method="POST" action="{{ route('chain.purchasing.orders.cancel',$order->id) }}" onsubmit="return confirm('Sipariş iptal edilsin mi?')">@csrf<button class="rounded-lg border border-rose-500/30 px-3 py-2 text-xs text-rose-300">İptal</button></form>@endif
                    </div>@endif
                </div>
            </article>
        @empty<p class="p-8 text-center text-sm text-slate-500">Henüz merkezi sipariş yok.</p>@endforelse</div>
        <div class="border-t border-slate-800 p-4">{{ $orders->links() }}</div>
    </section>
</div>

@if($canManage)
<div id="supplierModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4"><div class="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6"><div class="mb-5 flex justify-between"><h3 class="font-black">Yeni Tedarikçi</h3><button onclick="toggleModal('supplierModal',false)">✕</button></div><form method="POST" action="{{ route('chain.purchasing.suppliers.store') }}" class="space-y-3">@csrf<select name="branch_id" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Şube seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><input name="name" required placeholder="Tedarikçi adı" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><div class="grid gap-3 sm:grid-cols-2"><input name="contact_person" placeholder="Yetkili" class="rounded-lg border border-slate-700 bg-slate-950 p-3"><input name="phone" placeholder="Telefon" class="rounded-lg border border-slate-700 bg-slate-950 p-3"></div><input type="email" name="email" placeholder="E-posta" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Kaydet</button></form></div></div>

<div id="orderModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/80 p-4"><div class="w-full max-w-2xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div class="mb-5 flex justify-between"><h3 class="font-black">Yeni Satın Alma Siparişi</h3><button onclick="toggleModal('orderModal',false)">✕</button></div><form method="POST" action="{{ route('chain.purchasing.orders.store') }}" class="space-y-3">@csrf<div class="grid gap-3 sm:grid-cols-2"><select id="purchaseBranch" name="branch_id" required onchange="filterPurchaseOptions()" class="rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Şube seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><select id="purchaseSupplier" name="supplier_id" required class="rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Tedarikçi seçin</option>@foreach($suppliers->where('is_active',true) as $supplier)<option data-branch="{{ $supplier->branch_id }}" value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div><div class="grid gap-3 sm:grid-cols-2"><input type="date" name="order_date" value="{{ now()->toDateString() }}" required class="rounded-lg border border-slate-700 bg-slate-950 p-3"><input type="date" name="expected_delivery_date" class="rounded-lg border border-slate-700 bg-slate-950 p-3"></div><select id="purchaseProduct" name="items[0][product_id]" required class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"><option value="">Ürün seçin</option>@foreach($products as $product)<option data-branch="{{ $product->branch_id }}" value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }}</option>@endforeach</select><div class="grid gap-3 sm:grid-cols-3"><input type="number" step="0.001" min="0.001" name="items[0][quantity]" required placeholder="Miktar" class="rounded-lg border border-slate-700 bg-slate-950 p-3"><input type="number" step="0.0001" min="0" name="items[0][unit_price]" required placeholder="Birim fiyat" class="rounded-lg border border-slate-700 bg-slate-950 p-3"><input type="number" step="0.01" min="0" max="100" name="items[0][tax_rate]" value="20" placeholder="KDV %" class="rounded-lg border border-slate-700 bg-slate-950 p-3"></div><textarea name="notes" rows="2" placeholder="Sipariş notu" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-3"></textarea><button class="w-full rounded-xl bg-cyan-500 py-3 font-black text-slate-950">Sipariş Oluştur</button></form></div></div>
@endif
<script>function toggleModal(id,open){const e=document.getElementById(id);e.classList.toggle('hidden',!open);e.classList.toggle('flex',open)}function filterPurchaseOptions(){const branch=document.getElementById('purchaseBranch').value;['purchaseSupplier','purchaseProduct'].forEach(id=>{const select=document.getElementById(id);select.value='';select.querySelectorAll('option[data-branch]').forEach(option=>option.hidden=!branch||option.dataset.branch!==branch)})}filterPurchaseOptions()</script>
@endsection
