@extends('chain.layout')
@section('title','Üretim İş Akışı')
@section('content')
@php
    $statusMap=['planned'=>['Planlandı','border-blue-200 bg-blue-50 text-blue-700'],'in_progress'=>['Üretimde','border-amber-200 bg-amber-50 text-amber-700'],'completed'=>['Tamamlandı','border-emerald-200 bg-emerald-50 text-emerald-700'],'cancelled'=>['İptal','border-rose-200 bg-rose-50 text-rose-700']];
    $centralIngredientGroups=$centralIngredients->groupBy(fn($product)=>$product->category?->name??'Kategorisiz');
@endphp
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="institutional-page-kicker mb-1">Merkezi Üretim ve Reçete Yönetimi</p><h1>Üretim İş Akışı</h1><p class="mt-1 text-sm text-slate-500">Şubelerin planlanan yemek üretimlerini, hammadde tüketimini ve kalan stoklarını yönetin.</p></div><form method="GET" class="flex gap-2"><select name="branch_id" class="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm"><option value="">Tüm yetkili şubeler</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId===$branch->id)>{{ $branch->name }}</option>@endforeach</select><button class="institutional-action rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950">Filtrele</button></form></div>

@if($errors->any())<div class="mb-5 rounded-xl border border-rose-500/20 bg-rose-500/10 p-4 text-sm text-rose-400">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@if(session('success'))<div class="mb-5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-400">{{ session('success') }}</div>@endif

<div class="mb-5 flex flex-wrap items-center gap-2 rounded-xl border border-cyan-500/20 bg-cyan-500/5 px-4 py-3 text-xs"><strong class="mr-1 text-cyan-400">Merkezi katalog bağlı</strong><span class="rounded-full bg-slate-800 px-2.5 py-1">{{ $centralCategories->count() }} kategori</span><span class="rounded-full bg-slate-800 px-2.5 py-1">{{ $centralProducts->count() }} toplam ürün</span><span class="rounded-full bg-slate-800 px-2.5 py-1">{{ $centralIngredients->count() }} hammadde</span></div>

<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    @foreach([['Aktif Reçete',$stats['recipes'],'text-blue-500'],['Planlanan İş',$stats['planned'],'text-cyan-500'],['Üretimde',$stats['in_progress'],'text-amber-500'],['Bugün Tamamlanan',$stats['completed_today'],'text-emerald-500']] as [$label,$value,$color])<div class="institutional-metric rounded-xl border border-slate-800 bg-slate-900 p-5"><p class="institutional-metric-label">{{ $label }}</p><p class="institutional-metric-value mt-2 text-3xl font-semibold {{ $color }}">{{ $value }}</p></div>@endforeach
</div>

@if($canManage)
<div class="mt-5 grid gap-5 xl:grid-cols-2">
    <section class="rounded-xl border border-slate-800 bg-slate-900 p-5"><div class="mb-4"><h2 class="institutional-section-title">Şube Reçetesi Oluştur</h2><p class="text-xs text-slate-500">Ürün ve hammaddeler merkezi menüden gelir; reçete kaydedilince seçilen şubeye otomatik bağlanır.</p></div>
        <form method="POST" action="{{ route('chain.workflows.recipes.store') }}" class="space-y-3">@csrf
            <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-slate-500">Şube<select id="chainRecipeBranch" name="branch_id" required class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Seçin</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId===$branch->id)>{{ $branch->name }}</option>@endforeach</select></label><label class="text-xs text-slate-500">Reçete Adı<input name="name" required placeholder="Kuru Fasulye" class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></label><label class="text-xs text-slate-500">Merkezi Ürün <span class="text-cyan-500">({{ $centralProducts->count() }})</span><select name="output_menu_product_id" required class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Kategori / ürün seçin</option>@foreach($centralCategories as $category)<optgroup label="{{ $category->name }} · {{ $category->products->count() }} ürün">@foreach($category->products as $product)<option value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }}{{ $product->item_type==='raw_material'?' · Hammadde':'' }}{{ !$product->is_active?' · Pasif':'' }}</option>@endforeach</optgroup>@endforeach</select></label><label class="text-xs text-slate-500">Temel Porsiyon<input name="base_servings" required type="number" min="0.001" step="0.001" value="10" class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></label></div>
            <div><div class="mb-2 flex justify-between"><span class="text-xs font-semibold text-slate-500">Hammaddeler</span><button type="button" onclick="addChainIngredient()" class="text-xs font-semibold text-cyan-500">+ Malzeme</button></div><div id="chainIngredientRows" class="space-y-2"></div></div>
            <textarea name="instructions" rows="2" placeholder="Hazırlama notları" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></textarea><button class="institutional-action w-full rounded-lg bg-blue-600 p-2.5 text-sm font-semibold text-white">Reçeteyi Kaydet</button>
        </form>
    </section>
    <section class="rounded-xl border border-slate-800 bg-slate-900 p-5"><div class="mb-4"><h2 class="institutional-section-title">Üretim İş Emri Aç</h2><p class="text-xs text-slate-500">Şubeye, reçeteye ve hedef porsiyona göre plan oluşturun.</p></div>
        <form method="POST" action="{{ route('chain.workflows.store') }}" class="space-y-3">@csrf<label class="block text-xs text-slate-500">Şube / Reçete<select name="production_recipe_id" required class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"><option value="">Seçin</option>@foreach($recipes as $recipe)<option value="{{ $recipe->id }}">{{ $recipe->branch?->name }} · {{ $recipe->name }} ({{ number_format((float)$recipe->base_servings,0) }} baz)</option>@endforeach</select></label><div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-slate-500">Üretilecek Porsiyon<input name="planned_servings" required type="number" min="0.001" step="0.001" value="100" class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></label><label class="text-xs text-slate-500">Planlanan Zaman<input name="scheduled_for" type="datetime-local" value="{{ now()->format('Y-m-d\TH:i') }}" class="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></label></div><textarea name="notes" rows="2" placeholder="İş emri notu" class="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm"></textarea><button class="institutional-action w-full rounded-lg bg-cyan-500 p-2.5 text-sm font-semibold text-slate-950" @disabled($recipes->isEmpty())>İş Akışını Planla</button></form>
        <div class="mt-5 border-t border-slate-800 pt-4"><p class="text-xs leading-5 text-slate-500"><strong class="text-slate-300">Kontrollü stok işlemi:</strong> İş emri planlanınca stok değişmez. “Tamamla” işleminde tüm hammaddeler kilitlenip yeterlilik kontrolünden sonra birlikte düşülür.</p></div>
    </section>
</div>
@endif

<section class="mt-5"><div class="mb-3 flex items-end justify-between"><div><h2 class="institutional-section-title">Şube Üretim Takibi</h2><p class="text-xs text-slate-500">Gereken, mevcut ve üretim sonrası kalan miktarlar</p></div><span class="text-xs text-slate-500">{{ $workflows->total() }} iş emri</span></div><div class="space-y-4">
    @forelse($workflows as $workflow)
        @php([$statusLabel,$statusClass]=$statusMap[$workflow->status]??[$workflow->status,'border-slate-700 bg-slate-800 text-slate-400'])
        <article class="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div class="flex flex-wrap items-start justify-between gap-3 border-b border-slate-800 p-4"><div><div class="flex flex-wrap items-center gap-2"><h3 class="font-semibold">{{ $workflow->recipe_name }}</h3><span class="rounded-full border px-2 py-0.5 text-[10px] font-semibold {{ $statusClass }}">{{ $statusLabel }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $workflow->branch?->name }} · {{ $workflow->workflow_number }} · <strong>{{ number_format((float)$workflow->planned_servings,0) }} porsiyon</strong> · {{ $workflow->scheduled_for?->format('d.m.Y H:i')??'Plansız' }}</p></div>
            @if($canManage&&in_array($workflow->status,['planned','in_progress']))<div class="flex flex-wrap gap-2">@if($workflow->status==='planned')<form method="POST" action="{{ route('chain.workflows.start',$workflow) }}">@csrf<button class="rounded-lg border border-amber-500/30 px-3 py-2 text-xs font-semibold text-amber-500">Başlat</button></form>@endif<form method="POST" action="{{ route('chain.workflows.complete',$workflow) }}" onsubmit="return confirm('Hammaddeler şube stoğundan düşülecek. Devam edilsin mi?')">@csrf<button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Tamamla ve Stoktan Düş</button></form><form method="POST" action="{{ route('chain.workflows.cancel',$workflow) }}">@csrf<button class="rounded-lg px-3 py-2 text-xs font-semibold text-rose-500">İptal</button></form></div>@endif
        </div><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-xs"><thead class="bg-slate-950/50 uppercase text-slate-500"><tr><th class="p-3 pl-4">Hammadde</th><th class="p-3">Gereken</th><th class="p-3">Mevcut / Önceki</th><th class="p-3">Kalan</th><th class="p-3">Kontrol</th></tr></thead><tbody class="divide-y divide-slate-800">
            @if($workflow->items->isNotEmpty())@foreach($workflow->items as $item)<tr><td class="p-3 pl-4 font-semibold">{{ $item->product_name }}</td><td class="p-3">{{ number_format((float)$item->consumed_quantity,3,',','.') }} {{ $item->stock_unit }}</td><td class="p-3">{{ number_format((float)$item->stock_before,3,',','.') }} {{ $item->stock_unit }}</td><td class="p-3 text-emerald-500">{{ number_format((float)$item->stock_after,3,',','.') }} {{ $item->stock_unit }}</td><td class="p-3 text-emerald-500">Stok işlendi</td></tr>@endforeach
            @else @foreach($workflow->preview_requirements as $requirement)<tr><td class="p-3 pl-4 font-semibold">{{ $requirement->product->name }}</td><td class="p-3">{{ number_format($requirement->required,3,',','.') }} {{ $requirement->unit }}</td><td class="p-3">{{ number_format($requirement->available,3,',','.') }} {{ $requirement->unit }}</td><td class="p-3 {{ $requirement->sufficient?'text-emerald-500':'text-rose-500' }}">{{ number_format($requirement->available-$requirement->required,3,',','.') }} {{ $requirement->unit }}</td><td class="p-3 {{ $requirement->sufficient?'text-emerald-500':'text-rose-500' }}">{{ $requirement->sufficient?'Yeterli':'Eksik stok' }}</td></tr>@endforeach @endif
        </tbody></table></div></article>
    @empty<div class="rounded-xl border border-dashed border-slate-700 p-12 text-center text-sm text-slate-500">Seçilen kapsamda iş akışı bulunamadı.</div>@endforelse
</div><div class="mt-5">{{ $workflows->links() }}</div></section>

@if($canManage)<template id="chainIngredientTemplate"><div class="chain-ingredient-row grid grid-cols-12 gap-2"><select name="items[__INDEX__][menu_product_id]" required class="col-span-6 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs"><option value="">Merkezi hammadde ({{ $centralIngredients->count() }})</option>@foreach($centralIngredientGroups as $categoryName=>$categoryIngredients)<optgroup label="{{ $categoryName }} · {{ $categoryIngredients->count() }} hammadde">@foreach($categoryIngredients as $ingredient)<option value="{{ $ingredient->id }}">{{ $ingredient->name }} · {{ $ingredient->sku }} · {{ $ingredient->unit }}</option>@endforeach</optgroup>@endforeach</select><input name="items[__INDEX__][quantity]" required type="number" step="0.0001" min="0.0001" placeholder="Miktar" class="col-span-3 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs"><select name="items[__INDEX__][unit]" class="col-span-2 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs"><option>g</option><option>kg</option><option>ml</option><option>l</option><option>adet</option><option>porsiyon</option></select><button type="button" onclick="this.closest('.chain-ingredient-row').remove()" class="col-span-1 text-rose-500">×</button></div></template><script>let chainIngredientIndex=0;function addChainIngredient(){document.getElementById('chainIngredientRows').insertAdjacentHTML('beforeend',document.getElementById('chainIngredientTemplate').innerHTML.replaceAll('__INDEX__',chainIngredientIndex++))}addChainIngredient();</script>@endif
@endsection
