<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $branch->name }} · Diji Menü</title>
    <style>
        :root{color-scheme:dark;--bg:#090b10;--card:#151922;--line:#252b38;--accent:#ffc857;--muted:#929bad}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#fff;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.hero{padding:34px 20px 64px;background:radial-gradient(circle at 80% 0,#493515 0,transparent 42%),linear-gradient(145deg,#171b25,#090b10)}.wrap{width:min(1120px,100%);margin:auto}.brand{display:flex;align-items:center;gap:14px}.brand img{max-width:150px;max-height:48px;object-fit:contain}.brand b{font-size:18px}.hero h1{max-width:650px;margin:55px 0 12px;font-size:clamp(34px,7vw,66px);line-height:.98}.hero p{max-width:570px;color:#c7cbd3;line-height:1.7}.toolbar{position:sticky;top:0;z-index:5;padding:14px 20px;background:#090b10e8;border-bottom:1px solid var(--line);backdrop-filter:blur(16px)}.search{width:100%;padding:14px 16px;border:1px solid var(--line);border-radius:14px;background:#121620;color:#fff;outline:none}.tabs{display:flex;gap:8px;overflow:auto;padding:14px 0 2px}.tab{white-space:nowrap;border:1px solid var(--line);border-radius:999px;background:#121620;color:#b5bdcc;padding:9px 14px;cursor:pointer}.tab.active{background:var(--accent);border-color:var(--accent);color:#17130a;font-weight:800}.content{padding:26px 20px 70px}.section{margin:0 0 40px}.section h2{margin:0 0 16px;font-size:24px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px}.product{overflow:hidden;border:1px solid var(--line);border-radius:20px;background:var(--card);transition:.2s}.product:hover{transform:translateY(-3px);border-color:#66532b}.photo{height:160px;background:linear-gradient(135deg,#242b39,#121620);display:flex;align-items:center;justify-content:center;color:#596274}.photo img{width:100%;height:100%;object-fit:cover}.body{padding:16px}.body h3{margin:0 0 7px;font-size:17px}.body p{height:38px;margin:0;color:var(--muted);font-size:12px;line-height:1.5;overflow:hidden}.price{display:flex;align-items:end;justify-content:space-between;margin-top:15px}.price strong{color:var(--accent);font-size:19px}.old{margin-right:7px;color:#6e7685;font-size:12px;text-decoration:line-through}.badge{padding:5px 8px;border-radius:8px;background:#ffc85718;color:var(--accent);font-size:10px;font-weight:800}.empty{padding:70px 20px;text-align:center;color:var(--muted)}footer{border-top:1px solid var(--line);padding:24px;text-align:center;color:#697284;font-size:11px}@media(max-width:520px){.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.photo{height:125px}.body{padding:12px}.body p{display:none}.hero h1{margin-top:42px}}
    </style>
</head>
<body>
<header class="hero"><div class="wrap"><div class="brand">@if($organization?->logo_url)<img src="{{ $organization->logo_url }}" alt="{{ $organization->name }}">@endif<div><b>{{ $organization?->name ?? $branch->name }}</b><small style="display:block;color:#929bad">{{ $branch->name }}</small></div></div><h1>Lezzeti keşfet,<br><span style="color:var(--accent)">seçimini yap.</span></h1><p>Güncel ürünlerimizi, fiyatlarımızı ve size özel seçenekleri dijital menümüzde inceleyin.</p></div></header>
<div class="toolbar"><div class="wrap"><input id="search" class="search" placeholder="Menüde ara..." oninput="filterMenu()"><div class="tabs"><button class="tab active" data-cat="all" onclick="selectCategory(this)">Tümü</button>@foreach($categories as $category)<button class="tab" data-cat="{{ $category->id }}" onclick="selectCategory(this)">{{ $category->name }}</button>@endforeach</div></div></div>
<main class="content"><div class="wrap">@forelse($categories as $category)<section class="section" data-section="{{ $category->id }}"><h2>{{ $category->name }}</h2><div class="grid">@foreach($category->products as $product)<article class="product" data-cat="{{ $category->id }}" data-name="{{ mb_strtolower($product->name.' '.$product->description) }}"><div class="photo">@if($product->image_url)<img loading="lazy" src="{{ $product->image_url }}" alt="{{ $product->name }}">@else<span>Görsel yakında</span>@endif</div><div class="body"><h3>{{ $product->name }}</h3><p>{{ $product->description ?: 'Özenle hazırlanan lezzetli seçim.' }}</p><div class="price"><div>@if($product->discounted_price)<span class="old">₺{{ number_format((float)$product->price,2,',','.') }}</span>@endif<strong>₺{{ number_format($product->effective_price,2,',','.') }}</strong></div>@if($product->discounted_price)<span class="badge">İNDİRİM</span>@endif</div></div></article>@endforeach</div></section>@empty<div class="empty">Bu menüde henüz yayınlanmış ürün bulunmuyor.</div>@endforelse</div></main>
<footer>Diji Menü · {{ $branch->name }} · Adisyon altyapısıyla güncel</footer>
<script>let active='all';function selectCategory(btn){active=btn.dataset.cat;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));filterMenu()}function filterMenu(){const q=document.getElementById('search').value.toLocaleLowerCase('tr');document.querySelectorAll('.product').forEach(p=>p.hidden=!((active==='all'||p.dataset.cat===active)&&p.dataset.name.includes(q)));document.querySelectorAll('[data-section]').forEach(s=>{s.hidden=(active!=='all'&&s.dataset.section!==active)||![...s.querySelectorAll('.product')].some(p=>!p.hidden)})}</script>
</body></html>
